import type { Hero } from "./types";

export const HEROES: Hero[] = [
  {
    id: "boss-arunka",
    name: "Boss Arunka",
    short: "B.Arunka",
    element: "light",
    class: "knight",
    tier: "SS",
    roles: ["tank", "strip", "bruiser"],
    tags: ["defbreak", "barrier", "dual-attack", "soulburn", "strip"],
    effects: ["buff-dispel", "increase-cr", "dual-attack"],
    buffs: ["Ferocious Stand", "Increase Defense", "Barrier"],
    debuffs: ["Decrease Defense"],
    uniqueEffects: [
      {
        name: "Ferocious Stand",
        text: "Undispellable. Enemies cannot select allies other than her as a skill target.",
      },
      {
        name: "Vanguard of the Silent Expanse",
        text: "At battle start and end of turn, if she is in the front row, Ferocious Stand for 1 turn. After being attacked, +20% Combat Readiness.",
      },
    ],
    kit: "S1 Road Sign Smash: 60% Decrease Defense (damage scales with Defense). Soulburn: Dual Attack from the highest-Attack ally. S2 Vanguard of the Silent Expanse. S3 Coruscated Trajectory: strip all, Decrease Defense 2 turns, self Increase Defense + Barrier 2 turns (Defense scaling).",
    defense: 10,
    offense: 9,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "empyrean-ilynav",
    name: "Empyrean Ilynav",
    short: "E.Ilynav",
    element: "light",
    class: "knight",
    tier: "SS",
    roles: ["bruiser", "tank", "cleanse"],
    tags: ["injury", "soulburn", "cr-push"],
    effects: ["injury", "debuff-dispel", "increase-cr", "increase-pen-resist"],
    buffs: ["Indomitable"],
    uniqueEffects: [
      {
        name: "Dragon's Pride",
        text: "+20% Penetration Resistance to all allies. After every attack an ally suffers, she gains +10% Combat Readiness.",
      },
      {
        name: "Indomitable",
        text: "Undispellable. +30% Defense and Effect Resistance for 2 turns (from Unyielding Blow).",
      },
    ],
    kit: "S1 Sword of Punishment: vamp hit, up to 10% Injury (HP scaling). Soulburn: extra damage equal to 50% of Injury on the target, no Dual Attack. S2 Dragon's Pride. S3 Unyielding Blow: up to 20% Injury, cleanse two debuffs from all allies, Indomitable 2 turns.",
    defense: 9,
    offense: 9,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "lady-of-the-scales",
    name: "Lady of the Scales",
    short: "Scales",
    element: "light",
    class: "soulweaver",
    tier: "SS",
    roles: ["control", "healer"],
    tags: ["cr-push", "soulburn"],
    effects: ["damage-sharing", "debuff-dispel", "increase-cr"],
    buffs: ["Immortal", "Offering", "Abundance"],
    debuffs: ["Fear"],
    uniqueEffects: [
      {
        name: "Offering",
        text: "70% damage sharing of damage received by all allies. On lethal damage, Immortal 1 turn (once per battle).",
      },
      {
        name: "Abundance",
        text: "After attacking, inflicts 2,000 additional damage on the target.",
      },
      {
        name: "Scales of Equity",
        text: "Battle start: Offering on the foremost ally. When that ally dies, team heal 50%. When an enemy's Combat Readiness increases, she gains 35% of that amount (not from her own skill).",
      },
    ],
    kit: "S1 Divine Punishment: 50% Fear 1 turn, then team heal (target max-HP scaling). Soulburn 10: 100% chance, hits all, no dual attack. S2 Scales of Equity. S3 The Caress of Mercy: cleanse all, +15% CR, spend 20% HP of the Offering ally to grant Abundance 2 turns to the others.",
    defense: 9,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "new-moon-luna",
    name: "New Moon Luna",
    short: "NM Luna",
    element: "light",
    class: "mage",
    tier: "SS",
    roles: ["bruiser", "dps", "strip"],
    tags: ["injury", "aoe", "seal", "defbreak", "cr-push", "strip", "ignore-er", "soulburn"],
    effects: ["injury", "increase-cr", "buff-dispel"],
    debuffs: ["Decrease Defense", "Seal", "Cannot Buff"],
    uniqueEffects: [
      {
        name: "Skill Effect Nullifier",
        text: "Nullifies one effect from an enemy hero skill or artifact. She starts the fight with one stack.",
      },
    ],
    kit: "S1 HP-scaling poke and a small CR push. S2: 70% Decrease Defense, +50% CR, splash AoE. S3: strip all, then Seal and Cannot Buff for 2 turns. Starts with Skill Effect Nullifier. Soulburn ignores ER.",
    defense: 8,
    offense: 9,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "rinak",
    name: "Rinak",
    short: "Rinak",
    element: "earth",
    class: "thief",
    tier: "SS",
    roles: ["control", "opener", "strip"],
    tags: ["strip", "cr-cut", "extra-turn", "stun", "ignore-er", "soulburn"],
    effects: ["buff-dispel", "decrease-cr", "extra-turn"],
    buffs: ["Increase Attack", "Spoils"],
    debuffs: ["Pilfer", "Stun"],
    uniqueEffects: [
      {
        name: "Pilfer",
        text: "−20% Attack, Health, and Defense. Grants Spoils to the attacker. Heroes only. Remains even after dying.",
      },
      {
        name: "Spoils",
        text: "+20% Attack, Health, and Defense. Stacks up to 4. When dispelled, also dispels Pilfer from the caster.",
      },
    ],
    kit: "S1 Vital Point Slash: penetrate, no crit/heavy, Speed scaling. S2 Pickpocketing: strip all, −30% CR, Pilfer, self Increase Attack 2 turns, extra turn. Soulburn 20: ignore ER. S3 Clumsy Finish: penetrate Speed scaling, then self-strip + self-Stun 1 turn and 7,000 damage to all (hits even on miss). Ignores ER.",
    defense: 8,
    offense: 9,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "ruele-of-light",
    name: "Ruele of Light",
    short: "Ruele",
    element: "light",
    class: "soulweaver",
    tier: "SS",
    roles: ["revive", "healer", "cleanse"],
    tags: ["invincible", "barrier", "soulburn"],
    effects: ["revive", "debuff-dispel", "increase-cr", "damage-received-limit"],
    buffs: ["Invincible", "Barrier", "Damage Limit"],
    uniqueEffects: [
      {
        name: "Spirit Lord's Protection",
        text: "Undispellable. Granted at the start of the first battle. Upon dying, revives with 50% Health and +50% Combat Readiness.",
      },
    ],
    kit: "S1 Key to an Oath: poke then team heal (HP scaling). Soulburn 20: big team heal, no dual attack. S2 Light Pillar: cleanse an ally, heal, Barrier + Damage Limit (35% max HP) 2 turns. S3 Light Ascending: cleanse, full heal, Invincible 1 turn; if the target is dead, revive at 100% HP first.",
    defense: 10,
    offense: 5,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "school-nurse-yulha",
    name: "School Nurse Yulha",
    short: "SN Yulha",
    element: "dark",
    class: "thief",
    tier: "SS",
    roles: ["healer", "cleanse", "bruiser"],
    tags: ["counter", "barrier"],
    kit: "Shuts down aggro cleave with sustain and awkward counter pressure.",
    defense: 9,
    offense: 7,
  },
  {
    id: "harsetti",
    name: "Harsetti",
    short: "Harsetti",
    element: "dark",
    class: "mage",
    tier: "SS",
    roles: ["speedcap", "control"],
    tags: ["aoe", "defbreak", "extra-turn", "soulburn", "cr-cut"],
    effects: ["extra-turn", "buff-duration-decrease", "cannot-counterattack"],
    debuffs: ["Decrease Defense", "Decrease Attack", "Cannot Counterattack", "Cannot Buff"],
    uniqueEffects: [
      {
        name: "The Law of Skuggiheim",
        text: "PvP only. At battle start her Speed is fixed, and every other hero is capped at 90% of that Speed. On her turn, Combat Readiness increase does not apply.",
      },
    ],
    kit: "S1 Gambit: 60% Decrease Defense (soulburn: 100% and 2 turns), then En Passant AoE 60% Decrease Attack. HP scaling. S2 The Law of Skuggiheim. S3 Checkmate: −2 buff duration, 75% Cannot Counterattack and Cannot Buff, penetrate Defense. Full Focus spends for extra damage.",
    defense: 10,
    offense: 6,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "briar-witch-iseria",
    name: "Briar Witch Iseria",
    short: "B.Iseria",
    element: "dark",
    class: "ranger",
    tier: "SS",
    roles: ["strip", "dps"],
    tags: ["strip", "anti-revive", "ignore-er", "defbreak", "aoe", "soulburn"],
    effects: ["buff-dispel", "increase-hit"],
    buffs: ["Immortal"],
    debuffs: ["Decrease Defense", "Cannot Buff"],
    uniqueEffects: [
      {
        name: "Witch's Curse",
        text: "+35% Hit Chance. Allies and enemies cannot revive. On lethal damage, Immortal 1 turn.",
      },
    ],
    kit: "S1 Fallen Flower: 65% Decrease Defense 1 turn, extra Attack-scaling hit. S2 Witch's Curse. S3 Cursed Thorn: AoE strip all, 50% Decrease Defense 2 turns, 75% Cannot Buff 2 turns. Soulburn 20: ignores Effect Resistance.",
    defense: 4,
    offense: 10,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "ambitious-tywin",
    name: "Ambitious Tywin",
    short: "A.Tywin",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["opener", "strip", "tank"],
    tags: ["stun", "strip", "cr-push", "aoe"],
    kit: "Swiss-army opener: strip, stun, CR. Fits almost every offense draft.",
    defense: 6,
    offense: 9,
  },
  {
    id: "belian",
    name: "Belian",
    short: "Belian",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["soulblock", "bruiser"],
    tags: ["aoe", "strip", "extra-turn", "soulburn", "provoke", "cr-cut"],
    effects: ["extra-turn", "buff-dispel", "soul-removal", "decrease-cr"],
    buffs: ["Increase Defense", "Increase Effectiveness", "Increase Critical Hit Chance", "Continuous Healing"],
    debuffs: ["Decrease Speed", "Decrease Hit Chance", "Provoke"],
    uniqueEffects: [
      {
        name: "Shackles of Suppression",
        text: "Enemy soul gain is reduced by 100%. At the start of her turn, 70% chance to gain a random buff for 1 turn: Increase Effectiveness, Increase Critical Hit Chance, or Continuous Healing.",
      },
    ],
    kit: "S1 Light of Destruction: AoE 50% strip one buff; 35% Incursion (soulburn 100%) applies Decrease Speed and Decrease Hit Chance. HP scaling. S2 Shackles of Suppression. S3 Apocalypse: AoE CR cut 20–40%, Provoke, self Increase Defense 2 turns.",
    defense: 9,
    offense: 7,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "blood-moon-haste",
    name: "Blood Moon Haste",
    short: "BM Haste",
    element: "dark",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "revive", "strip", "dps"],
    tags: ["strip", "immunity", "soulburn", "ignore-er", "barrier"],
    effects: ["buff-dispel", "revive"],
    buffs: ["Barrier", "Immunity", "Blood Aura", "Immortal"],
    uniqueEffects: [
      {
        name: "Blood Aura",
        text: "Undispellable. +30% Effectiveness and Speed. Moon Slash deals +100% damage while this is up.",
      },
      {
        name: "Grudge",
        text: "Attacks penetrate and cannot crit or heavy blow. When an ally dies: team Barrier + Immunity 2 turns, self Blood Aura 2 turns. 4-turn cooldown.",
      },
    ],
    kit: "S1 Blood Scythe: strip one, HP scaling; on strip, Bloody Retribution extra attack (team heal, HP scaling). Soulburn 10: ignore ER. S2 Grudge. S3 Moon Slash: strip all, then hit; if the target dies, revive all dead allies and grant Immortal 1 turn. Blood Aura doubles S3 damage.",
    defense: 6,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "conqueror-lilias",
    name: "Conqueror Lilias",
    short: "C.Lilias",
    element: "light",
    class: "warrior",
    tier: "S",
    roles: ["opener", "control"],
    tags: ["dual-attack", "cr-push", "provoke", "extra-turn", "defbreak", "soulburn", "barrier"],
    effects: ["dual-attack", "extra-turn", "increase-cr", "buff-duration-decrease"],
    buffs: ["Vigor", "Barrier"],
    debuffs: ["Redirected Provoke", "Decrease Defense", "Decrease Attack"],
    uniqueEffects: [
      {
        name: "Vigor",
        text: "Undispellable. +30% Attack and Defense.",
      },
      {
        name: "Redirected Provoke",
        text: "At the start of the turn, forcibly uses basic skill on the enemy with the highest max Health.",
      },
    ],
    kit: "S1 Kneel Down: Dual Attack from a random ally (no soulburn). S2 Cover!: 70% Redirected Provoke + Decrease Defense 1 turn, Barrier on her and the highest-HP ally 2 turns. Soulburn 10: those debuffs last +1 turn. S3 For Honor!: team Vigor 2 turns, +15% CR, −1 enemy buff duration, 75% Decrease Attack 2 turns, extra turn.",
    defense: 7,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "death-dealer-ray",
    name: "Death Dealer Ray",
    short: "DD Ray",
    element: "dark",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "cleanse", "dps"],
    tags: ["aoe", "barrier"],
    kit: "Heals, cleanses, and still deals damage in long fights.",
    defense: 7,
    offense: 7,
  },
  {
    id: "dragon-bride-senya",
    name: "Dragon Bride Senya",
    short: "DB Senya",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["tank", "bruiser", "cleanse"],
    tags: ["barrier", "aoe", "cr-push", "soulburn"],
    effects: ["increase-cr", "debuff-dispel"],
    buffs: ["Increase Speed", "Barrier", "Oath of Punishment"],
    uniqueEffects: [
      {
        name: "Oath of Punishment",
        text: "Undispellable. Immune to debuffs and some harmful effects. After attacking on her turn, inflicts 4,000 additional damage.",
      },
      {
        name: "Bride's Resolve",
        text: "+10% max Health. When the back-row ally (not her) is at 50% HP or less after being attacked: cleanse her and that ally, then Bridal Prayer — Barrier on both for 3 turns, Oath of Punishment on her for 3 turns, and her skill cooldowns reset. Gains 10 Soul.",
      },
    ],
    kit: "S1 One Step: poke, self Increase Speed 1 turn (HP scaling). S2 Bride's Resolve (back-row trigger). S3 Overcoming Hardship: pierce (no crit/heavy), +30% CR to her and the back-row ally; with Oath of Punishment this hits all enemies. Soulburn −2 cooldown.",
    defense: 9,
    offense: 6,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "fallen-cecilia",
    name: "Fallen Cecilia",
    short: "F.Cecilia",
    element: "dark",
    class: "knight",
    tier: "S",
    roles: ["tank", "strip"],
    tags: ["barrier", "provoke", "aoe", "soulburn", "ignore-er"],
    effects: ["buff-dispel", "damage-reduction"],
    buffs: ["Barrier", "Skill Nullifier"],
    debuffs: ["Provoke"],
    uniqueEffects: [
      {
        name: "Strong Instinct",
        text: "50% additional damage reduction to all allies (hero extra damage only; strongest copy wins). At battle start, team Barrier 2 turns. At the end of her turn, Barrier on the lowest-HP ally for 2 turns (HP scaling).",
      },
      {
        name: "Skill Nullifier",
        text: "Nullifies damage from skills (once, granted to all allies by Spear of Resentment).",
      },
    ],
    kit: "S1 Mistake: 85% Provoke (soulburn ignores ER). HP scaling. S2 Strong Instinct. S3 Spear of Resentment: AoE strip all buffs, transfer her debuffs onto the hit, grant Skill Nullifier once to all allies.",
    defense: 9,
    offense: 4,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "frieren",
    name: "Frieren",
    short: "Frieren",
    element: "earth",
    class: "mage",
    tier: "S",
    roles: ["control", "dps", "strip"],
    tags: ["aoe", "strip", "immunity", "soulburn", "cr-push"],
    effects: ["buff-dispel", "increase-cr"],
    buffs: ["Immunity", "Defensive Magic", "Increase Attack"],
    uniqueEffects: [
      {
        name: "Defensive Magic",
        text: "Undispellable. When attacked, consumes 4 Soul and nullifies damage from skills.",
      },
      {
        name: "The Highest Form of Magic",
        text: "Battle start: +40% Fighting Spirit and Focus to all allies. At 4+ Soul, grants Defensive Magic. After being attacked, all allies +7% Combat Readiness.",
      },
    ],
    kit: "S1 Ordinary Offensive Magic: self Immunity 1 turn; on her turn, Vollzanbel extra attack (AoE, lost-HP scaling, +1 Soul). Soulburn 10: more S1 damage. S2 The Highest Form of Magic. S3 Judradjim: self Increase Attack 3 turns, AoE strip all, +50% CR, 50% penetrate.",
    defense: 7,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "genesis-ras",
    name: "Genesis Ras",
    short: "G.Ras",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["opener", "tank"],
    tags: ["seal", "extra-turn", "soulburn", "ignore-er", "cr-push"],
    effects: ["revive", "extra-turn", "increase-cr"],
    buffs: ["Sacred Covenant"],
    debuffs: ["Seal", "Collapse"],
    uniqueEffects: [
      {
        name: "Sacred Covenant",
        text: "Undispellable. Immune to debuffs. Upon dying, revives with 100% Health. Granted 5 turns at the start of the first battle.",
      },
      {
        name: "Collapse",
        text: "−25% max Health. Doubled on heroes (50%).",
      },
    ],
    kit: "S1 Sacred Blade: +25% CR, HP scaling. S2 Chains of Sealing: Seal + Collapse 2 turns, then hit; crit = extra turn. Soulburn 10: ignore ER. S3 Goddess's Judgment: AoE penetrate (HP scaling, more damage vs fewer targets). Battle start: Sacred Covenant 5 turns.",
    defense: 7,
    offense: 9,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "lone-wolf-peira",
    name: "Lone Wolf Peira",
    short: "LW Peira",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["opener", "cleanse"],
    tags: ["evade", "extra-turn", "cr-push", "defbreak", "soulburn", "aoe"],
    effects: ["extra-turn", "increase-cr", "increase-evasion", "debuff-dispel"],
    buffs: ["Rampage", "Swift Attack"],
    debuffs: ["Decrease Defense"],
    uniqueEffects: [
      {
        name: "Rampage",
        text: "Undispellable. +20% Speed and Evasion. Granted to Dark allies for 3 turns from S3.",
      },
      {
        name: "Time to Rampage",
        text: "+35% Evasion. Start of turn: +20% Attack (stacks 5). End of turn: all allies +10% Combat Readiness.",
      },
      {
        name: "Swift Attack",
        text: "End of the bearer's turn: +50% Combat Readiness, then this buff falls off.",
      },
    ],
    kit: "S1 Bash: 60% Decrease Defense 1 turn. Soulburn 10: AoE, no Dual Attack. S2 Time to Rampage. S3 Hound the Indolent: cleanse 2 from all allies, Rampage on Dark allies 3 turns, Swift Attack on allies (not her), extra turn. 8-turn cooldown. Not a stripper.",
    defense: 6,
    offense: 9,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "sea-phantom-politis",
    name: "Sea Phantom Politis",
    short: "SP Politis",
    element: "dark",
    class: "ranger",
    tier: "S",
    roles: ["strip", "control"],
    tags: ["strip", "dual-attack", "cr-cut", "ignore-er", "soulburn", "aoe"],
    effects: ["buff-dispel", "decrease-cr", "resource-reduction", "dual-attack"],
    buffs: ["Rage", "Stealth"],
    debuffs: ["Decrease Speed"],
    uniqueEffects: [
      {
        name: "Rage",
        text: "Undispellable. +20% Attack and Speed.",
      },
      {
        name: "Phantom's Waltz",
        text: "Enemy resource gain −50% (Focus, Fighting Spirit, etc). Start of battle and end of turn: 60% Stealth 1 turn. Not a soul lock.",
      },
      {
        name: "Stealth",
        text: "Cannot be singled out while an ally is alive. AoE grants damage reduction, then Stealth falls off after taking the hit.",
      },
    ],
    kit: "S1 Graceful Gesture: strip one; while Enraged, Dual Attack from the highest-Attack ally. S2 Phantom's Waltz. S3 Fanatic Ball: team Rage 2 turns, AoE strip two, Decrease Speed 2 turns, −20% CR. Soulburn 20: ignore ER. Not soulblock — that is Belian.",
    defense: 7,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "setsuka",
    name: "Setsuka",
    short: "Setsuka",
    element: "fire",
    class: "thief",
    tier: "S",
    roles: ["evasion", "dps", "strip"],
    tags: ["evade", "counter", "aoe", "strip", "ignore-er", "soulburn"],
    effects: ["increase-evasion", "counterattack", "buff-dispel", "increase-cr", "ignore-damage-sharing"],
    buffs: ["Demon Blade Unleashed"],
    debuffs: ["Beguile", "Decrease Hit Chance"],
    uniqueEffects: [
      {
        name: "Demon Blade Unleashed",
        text: "+200% Attack and cannot die for a number of turns. Cannot be subject to damage-sharing effects.",
      },
      {
        name: "Suppressed Desire",
        text: "+30% Evasion to all allies. When an ally other than her evades, she counterattacks. At full Fighting Spirit after an attack: consume it, gain Demon Blade Unleashed 1 turn, then Blade Art: Bewitching Blossom — spend all HP to AoE (lost-HP scaling) and +50% CR.",
      },
    ],
    kit: "S1 Horizontal Slash: vamp hit (HP scaling). Soulburn: more damage. S2 Suppressed Desire. S3 Rouge Aroma: strip all, Beguile + Decrease Hit Chance 2 turns. Ignores ER vs lower max-HP targets. Beguile: end of turn, 10% max-HP damage to their allies (heroes), then dispels.",
    defense: 8,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "witch-of-the-mere-tenebria",
    name: "Witch of the Mere Tenebria",
    short: "WMeri",
    element: "light",
    class: "mage",
    tier: "S",
    roles: ["control", "dps"],
    tags: ["stun", "cr-cut", "aoe"],
    kit: "Control mage with stun chains. Holds mid-rank and still drafts in RTA.",
    defense: 6,
    offense: 8,
  },
  {
    id: "shepherd-diene",
    name: "Shepherd of the Dark Diene",
    short: "ML Diene",
    element: "dark",
    class: "mage",
    tier: "S",
    roles: ["dps", "strip", "control"],
    tags: ["strip", "seal", "dual-attack", "cr-cut", "cr-push", "ignore-er", "soulburn", "aoe"],
    effects: ["buff-dispel", "debuff-dispel", "decrease-cr", "increase-cr", "dual-attack", "always-crit"],
    buffs: ["Immortal"],
    debuffs: ["Rupture", "Seal"],
    uniqueEffects: [
      {
        name: "Noias's Guidance",
        text: "Battle start: Immortal 1 turn. While Immortal, +200% Effect Resistance. When anyone Soulburns, cleanse herself and activate Dark Moon.",
      },
      {
        name: "Dark Moon",
        text: "AoE strip two buffs, then self Immortal 3 turns and +35% Combat Readiness.",
      },
      {
        name: "Rupture",
        text: "When attacked, additional damage proportional to max Health. Heroes only.",
      },
    ],
    kit: "S1 Crimson Claws: Rupture 1 turn, always crit, HP scaling; while Immortal, Dual Attack from the highest-Attack ally. Soulburn 20: more damage. S2 Noias's Guidance. S3 Endless Darkness: AoE Seal 2 turns, −30% CR, always crit, HP scaling; while Immortal, ignore ER.",
    defense: 7,
    offense: 9,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "urban-shadow-choux",
    name: "Urban Shadow Choux",
    short: "US Choux",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["injury", "aoe", "cr-push", "soulburn"],
    effects: ["injury", "increase-cr"],
    buffs: ["Bzzt!", "Increase Speed"],
    uniqueEffects: [
      {
        name: "Bzzt!",
        text: "Undispellable. After attacking, 2,000 extra damage and up to 10% injury to all enemies.",
      },
      {
        name: "Wild Charge",
        text: "+20% Crit Chance. Start of turn: +1 Focus and Bzzt! 1 turn. Full Focus resets S3 cooldown.",
      },
    ],
    kit: "S1 Zippity Zap!: +15% CR, HP scaling; on her turn +1 Focus. Soulburn 10: more damage. S2 Wild Charge. S3 Operation: Cream Pastry: up to 25% injury, team Increase Speed 2 turns; full Focus: consume all, heal, extra damage = 60% of injury on the target. AoE injury is Bzzt!, not the S3.",
    defense: 7,
    offense: 9,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "last-rider-krau",
    name: "Last Rider Krau",
    short: "LR Krau",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["tank", "dps"],
    tags: ["immunity", "aoe", "barrier", "soulburn"],
    effects: ["ally-cd-decrease"],
    buffs: ["Increase Speed", "Barrier", "Immunity"],
    uniqueEffects: [
      {
        name: "Code Number 00",
        text: "After being attacked, skill cooldowns −1. After an attack that hits all allies, extra −1 cooldown and a team Barrier (HP scaling) for 2 turns.",
      },
    ],
    kit: "S1 Punishment: hit then self Increase Speed 1 turn (HP scaling). S2 Code Number 00. S3 Mobile Weapon Ziegfried: AoE penetrate (no crit/heavy), team Immunity 2 turns, −1 skill cooldown. Damage scales with HP and Speed and stacks up to 3 uses. Soulburn −2 cooldown.",
    defense: 9,
    offense: 7,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "navy-captain-landy",
    name: "Navy Captain Landy",
    short: "NC Landy",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["aoe", "stun", "cr-push", "soulburn"],
    effects: ["increase-cr", "increase-crit-resist"],
    buffs: ["Increase Attack", "Increase Critical Hit Resistance"],
    debuffs: ["Stun"],
    uniqueEffects: [
      {
        name: "Ruler of the Sea",
        text: "Immune to Stun, Sleep, and Fear. +50% Crit Resistance. Battle start: +50% Crit Resistance to allies (not her) for 2 turns. After attacking: +10% Attack, stacks 5.",
      },
      {
        name: "Salvo Fire",
        text: "Extra attack: AoE artillery, then she heals (Attack scaling). 40% after S1, 100% on soulburn.",
      },
      {
        name: "Mobilize the Warship",
        text: "Spend 100 Fighting Spirit. Self Attack up 3 turns, AoE Stun 1 turn, 60% Defense penetration.",
      },
    ],
    kit: "S1 Precision Targeting: +20% CR, +25 Fighting Spirit; 40% Salvo Fire extra attack. Soulburn 10: 100% Salvo Fire. S2 Ruler of the Sea. S3 Mobilize the Warship: 100 FS. Not Dual Attack, not a counter unit.",
    defense: 7,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "hecate",
    name: "Hecate",
    short: "Hecate",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["anti-revive", "aoe", "cr-push"],
    effects: ["extinction", "ignore-damage-sharing", "increase-cr", "ally-cd-decrease"],
    buffs: ["Stealth", "Increase Attack", "Increase Attack (Greater)"],
    uniqueEffects: [
      {
        name: "Death's Dominion",
        text: "All heroes cannot revive and cannot be granted Immortality. Her attacks penetrate 85% Defense and cannot crit or heavy blow.",
      },
      {
        name: "Final Deliverance",
        text: "On her turn, S1 extra-attacks all enemies, then Stealth 1 turn and −2 skill cooldowns.",
      },
    ],
    kit: "S1 Reaper's Scythe: +20% CR; on her turn, Final Deliverance. S2 Death's Dominion. S3 Inescapable Demise: self Attack up 3 turns, then hit; vs heroes, ignore damage share. First battle starts S3 on cooldown. Soulburn 10: Attack (Greater). Not injury.",
    defense: 6,
    offense: 9,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "notos",
    name: "Notos",
    short: "Notos",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["tank", "control"],
    tags: ["stun", "barrier", "immunity"],
    kit: "Frontline control knight. Hard to draft around if left open.",
    defense: 8,
    offense: 7,
  },
  {
    id: "eternal-wanderer-ludwig",
    name: "Eternal Wanderer Ludwig",
    short: "EW Ludwig",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["cleave", "dps"],
    tags: ["aoe", "soulburn", "defbreak"],
    kit: "Soulburn cleave mage. Strong until Emperor, where evasion walls eat him.",
    defense: 3,
    offense: 8,
  },
  {
    id: "remnant-violet",
    name: "Remnant Violet",
    short: "R.Violet",
    element: "dark",
    class: "thief",
    tier: "A",
    roles: ["evasion", "dps"],
    tags: ["evade", "extra-turn", "soulburn", "cr-push"],
    effects: ["increase-evasion", "extra-turn", "increase-cr"],
    buffs: ["Increase Attack"],
    debuffs: ["Decrease Hit Chance"],
    uniqueEffects: [
      {
        name: "Concentration",
        text: "+35% Evasion. On evade, gain 1 Focus. After attacking or being attacked, if Focus is 5, activate Massacre on a random enemy and consume all Focus.",
      },
    ],
    kit: "S1 Sword Flash: 60% Decrease Hit Chance. Soulburn 20: extra turn. S2 Concentration. S3 Massacre: Increase Attack 3 turns, then hit with 50% penetrate and +50% CR. Massacre also auto-fires from Concentration at 5 Focus.",
    defense: 8,
    offense: 7,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "ran",
    name: "Ran",
    short: "Ran",
    element: "ice",
    class: "thief",
    tier: "A",
    roles: ["opener", "strip"],
    tags: ["strip", "cr-push", "defbreak"],
    kit: "Classic ice opener. Still climbs mid-high if the speed floor is real.",
    defense: 3,
    offense: 8,
  },
  {
    id: "apocalypse-ravi",
    name: "Apocalypse Ravi",
    short: "A.Ravi",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps", "revive"],
    tags: ["injury", "soulburn", "cr-push"],
    effects: ["injury", "increase-cr", "revive"],
    buffs: ["Skill Nullifier", "War God"],
    uniqueEffects: [
      {
        name: "War God's Might",
        text: "+30% Penetration Resistance. First battle: 50 Fighting Spirit. After being hit: spend 10 FS, +15% Combat Readiness, heal (HP scaling).",
      },
      {
        name: "War God",
        text: "When an ally dies: +50% Defense Penetration on Deliverance: Soul Exchange, then this buff falls off. Also resets that skill's cooldown.",
      },
      {
        name: "Deliverance: Soul Exchange",
        text: "On a kill: revive a random dead ally at 30% HP, +100% Combat Readiness, Skill Nullifier once. HP scaling.",
      },
    ],
    kit: "S1 Spectral Axe: up to 10% injury, lifesteal, HP scaling, +20 Fighting Spirit. Soulburn 20: huge damage, no Dual Attack. S2 War God's Might. S3 Deliverance: Soul Exchange. Injury is real. Revive is on a kill, not a Ruele reset.",
    defense: 8,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "mediator-kawerik",
    name: "Mediator Kawerik",
    short: "ML Kawerik",
    element: "dark",
    class: "warrior",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["cr-cut", "seal"],
    kit: "Blocks combat-readiness transfers. Wrecks CR-push compositions.",
    defense: 6,
    offense: 8,
  },
  {
    id: "maid-chloe",
    name: "Maid Chloe",
    short: "Maid Chloe",
    element: "light",
    class: "soulweaver",
    tier: "A",
    roles: ["revive", "healer"],
    tags: ["invincible", "barrier"],
    kit: "Revive option if Ruele is missing. Still holds Champion defenses.",
    defense: 8,
    offense: 4,
  },
  {
    id: "spirit-eye-celine",
    name: "Spirit Eye Celine",
    short: "SE Celine",
    element: "light",
    class: "thief",
    tier: "S",
    roles: ["revive", "dps", "cleanse"],
    tags: ["extra-turn", "soulburn", "counter"],
    effects: ["revive", "extra-turn", "damage-received-limit", "debuff-dispel", "counterattack"],
    buffs: ["Increase Attack", "Immortal", "Possession"],
    uniqueEffects: [
      {
        name: "Sixth Sense",
        text: "Damage from one attack cannot exceed 70% of max Health. When a hero dies: skill cooldowns −1 and +5 Soul.",
      },
      {
        name: "Spirit Gate: Burning Possession",
        text: "Revive all dead allies. Cleanse all, team Immortal 1 turn, Possession on herself 3 turns.",
      },
      {
        name: "Possession",
        text: "Undispellable. +25% Attack. Counterattacks when hit by a critical hit.",
      },
      {
        name: "Nimble Sword",
        text: "Used instead of S1 if she has a buff and it is not a Dual Attack. +50% Attack 1 turn, lifesteal, 50% Defense penetration. No Dual Attack.",
      },
    ],
    kit: "S1 Mighty Strike / Nimble Sword. Soulburn 20: extra turn. S2 Sixth Sense. S3 Spirit Gate: Burning Possession — revive all, cleanse all, Immortal 1 turn. Not an evasion unit. Not a stripper.",
    defense: 7,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "abyssal-yufine",
    name: "Abyssal Yufine",
    short: "A.Yufine",
    element: "dark",
    class: "knight",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["stun", "aoe", "defbreak"],
    kit: "Stun into damage. A reliable flex DPS into clumped defenses.",
    defense: 5,
    offense: 8,
  },
  {
    id: "amid",
    name: "Amid",
    short: "Amid",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["cr-push", "immunity"],
    kit: "CR-push healer. Enables extra turns for your win condition.",
    defense: 6,
    offense: 7,
  },
  {
    id: "choux",
    name: "Choux",
    short: "Choux",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["bruiser", "tank"],
    tags: ["barrier", "counter"],
    kit: "Barrier bruiser. Simple, tanky, and still drafts on defense.",
    defense: 7,
    offense: 6,
  },
  {
    id: "closer-charles",
    name: "Closer Charles",
    short: "C.Charles",
    element: "dark",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "defbreak"],
    kit: "Extra-attack thief. Punishes buffed walls if the strip lands.",
    defense: 4,
    offense: 8,
  },
  {
    id: "crimson-armin",
    name: "Crimson Armin",
    short: "C.Armin",
    element: "light",
    class: "knight",
    tier: "A",
    roles: ["tank"],
    tags: ["provoke", "barrier", "invincible"],
    kit: "Provoke tank. Classic anti-cleave piece for Gold through Master.",
    defense: 8,
    offense: 3,
  },
  {
    id: "diene",
    name: "Diene",
    short: "Diene",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["barrier", "cr-push", "soulburn"],
    effects: ["increase-cr", "debuff-dispel", "ally-cd-decrease", "increase-pen-resist"],
    buffs: ["Increase Attack", "Barrier", "Increase Defense", "Increase Penetration Resistance"],
    kit: "S1 Light of Judgment: +10% CR, doubled if she has a buff. S2 Blessings of the Goddess: team Increase Attack + Barrier 2 turns, then +15% CR. S3 Saint's Prayer: team cleanse, Increase Defense + Increase Penetration Resistance 3 turns, self +50% CR. Soulburn 20: all skill cooldowns −2. No immunity.",
    defense: 5,
    offense: 7,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "elena",
    name: "Elena",
    short: "Elena",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["aoe", "cr-cut"],
    kit: "AoE cleanse and CR cut. Softens control teams.",
    defense: 6,
    offense: 5,
  },
  {
    id: "eligos",
    name: "Eligos",
    short: "Eligos",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "defbreak"],
    kit: "Fire ranger DPS. Useful as a dedicated cleave closer.",
    defense: 3,
    offense: 7,
  },
  {
    id: "jenua",
    name: "Jenua",
    short: "Jenua",
    element: "fire",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "defbreak"],
    kit: "Single-target assassin. Deletes a key unit if he takes the turn.",
    defense: 3,
    offense: 8,
  },
  {
    id: "krau",
    name: "Krau",
    short: "Krau",
    element: "ice",
    class: "knight",
    tier: "A",
    roles: ["tank", "dps"],
    tags: ["provoke", "fixed-dmg", "invincible"],
    kit: "HP-scaling nuke on S3. Still a Champion-viable surprise defense.",
    defense: 7,
    offense: 6,
  },
  {
    id: "lilias",
    name: "Lilias",
    short: "Lilias",
    element: "fire",
    class: "knight",
    tier: "A",
    roles: ["opener", "tank"],
    tags: ["cr-push", "provoke", "aoe"],
    kit: "CR-push opener with provoke. Budget G.Ras for many accounts.",
    defense: 6,
    offense: 7,
  },
  {
    id: "milim",
    name: "Milim",
    short: "Milim",
    element: "fire",
    class: "mage",
    tier: "A",
    roles: ["cleave", "dps"],
    tags: ["aoe", "soulburn", "extra-turn"],
    kit: "Soulburn cleave. Mid-rank ladder tool, falls off versus evasion.",
    defense: 2,
    offense: 8,
  },
  {
    id: "mort",
    name: "Mort",
    short: "Mort",
    element: "earth",
    class: "knight",
    tier: "S",
    roles: ["tank", "bruiser"],
    tags: ["defbreak", "barrier", "counter", "ignore-er", "soulburn", "aoe"],
    effects: ["counterattack", "cannot-counterattack"],
    buffs: ["Barrier", "Increase Speed"],
    debuffs: ["Decrease Defense", "Fear"],
    uniqueEffects: [
      {
        name: "Absolute Dignity",
        text: "Immune to Stun, Sleep, and Fear. All other heroes cannot counterattack. When an ally is hit, 20% chance he counters.",
      },
      {
        name: "Sacred Blessing",
        text: "On his counter: team Barrier 2 turns (HP scaling) and self Increase Speed 2 turns. 3-turn cooldown.",
      },
    ],
    kit: "S1 Extermination: 40% Decrease Defense 2 turns, HP scaling; ignore ER vs lower max HP. Soulburn 10: 100% def break. S2 Absolute Dignity. S3 Advent: Mortelix: AoE Fear 2 turns, self heal, 70% penetrate vs highest-HP enemy, ignore ER vs lower max HP. Not soulblock — that is Belian.",
    defense: 8,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "nahkwol",
    name: "Nahkwol",
    short: "Nahkwol",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["unhealable", "defbreak"],
    kit: "Unhealable ranger. Pairs with injury to stop walls from recovering.",
    defense: 5,
    offense: 7,
  },
  {
    id: "pirate-captain-flan",
    name: "Pirate Captain Flan",
    short: "PC Flan",
    element: "dark",
    class: "ranger",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "cr-push", "defbreak"],
    kit: "Strip plus CR. A cleaner Ran-line opener for dark-heavy drafts.",
    defense: 4,
    offense: 8,
  },
  {
    id: "politis",
    name: "Politis",
    short: "Politis",
    element: "fire",
    class: "mage",
    tier: "S",
    roles: ["control"],
    tags: ["stun", "cr-push", "extra-turn", "soulburn", "aoe"],
    effects: ["extra-turn", "increase-cr", "buff-duration-decrease"],
    debuffs: ["Stun", "Decrease Hit Chance", "Cannot Buff"],
    uniqueEffects: [
      {
        name: "Astral Guide",
        text: "Vs non-Elite/Boss: Combat Readiness increases they receive are −50%. When an enemy uses a non-attack skill, Tranquility.",
      },
      {
        name: "Tranquility",
        text: "AoE: −1 buff duration on all enemies, then she gains +30% Combat Readiness. 2-turn cooldown.",
      },
    ],
    kit: "S1 Call of the Stars: 25% Stun. Soulburn 20: extra turn. S2 Astral Guide. S3 Starfall: AoE 75% Decrease Hit Chance + Cannot Buff 2 turns. Not soulblock — that is Belian.",
    defense: 7,
    offense: 7,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "requiem-roana",
    name: "Requiem Roana",
    short: "RQ Roana",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["healer", "control"],
    tags: ["counter", "barrier"],
    kit: "Anti-extra-turn healer. Punishes dual-attack and extra-attack cores.",
    defense: 8,
    offense: 5,
  },
  {
    id: "roy-mustang",
    name: "Roy Mustang",
    short: "Mustang",
    element: "fire",
    class: "mage",
    tier: "A",
    roles: ["cleave", "dps"],
    tags: ["aoe", "defbreak", "soulburn"],
    kit: "AoE fire mage. Mid-ladder cleave closer with a high damage ceiling.",
    defense: 2,
    offense: 8,
  },
  {
    id: "sage-baal",
    name: "Sage Baal & Sezan",
    short: "Sage Baal",
    element: "light",
    class: "mage",
    tier: "A",
    roles: ["control", "cleave"],
    tags: ["stun", "aoe", "cr-cut"],
    kit: "AoE stun mage. G.Ras exists specifically to make this unit sad.",
    defense: 5,
    offense: 8,
  },
  {
    id: "schniel",
    name: "Schniel",
    short: "Schniel",
    element: "earth",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "cr-push"],
    kit: "Cleanse plus immunity soul weaver. Stabilizes bruiser drafts.",
    defense: 6,
    offense: 6,
  },
  {
    id: "shalltear",
    name: "Shalltear",
    short: "Shalltear",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["aoe", "defbreak"],
    kit: "Fire warrior DPS with a greedy damage profile. Needs setup.",
    defense: 4,
    offense: 7,
  },
  {
    id: "sharun",
    name: "Sharun",
    short: "Sharun",
    element: "earth",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "control"],
    tags: ["barrier", "cr-push"],
    kit: "Support that enables turn-2. Often paired with Fenne-style control.",
    defense: 6,
    offense: 6,
  },
  {
    id: "solitaria",
    name: "Solitaria of the Snow",
    short: "Solitaria",
    element: "light",
    class: "mage",
    tier: "S",
    roles: ["control", "strip"],
    tags: ["strip", "stun", "cr-cut", "extra-turn", "soulburn", "barrier", "aoe"],
    effects: ["buff-dispel", "decrease-cr", "extra-turn", "buff-duration-decrease", "resource-reduction"],
    buffs: ["Daydream", "Stealth", "Barrier"],
    debuffs: ["Stun", "Decrease Attack", "Decrease Hit Chance", "Decrease Speed", "Cannot Buff"],
    uniqueEffects: [
      {
        name: "Daydream",
        text: "Undispellable. After attacking, inflicts a random 1-turn debuff: Decrease Attack, Decrease Hit Chance, Decrease Speed, or Cannot Buff.",
      },
      {
        name: "I Wanna Go Home",
        text: "Enemy Focus gain is 0. Start of turn: 70% Daydream 1 turn. End of turn: 70% Stealth 1 turn.",
      },
      {
        name: "Stealth",
        text: "Cannot be singled out while an ally is alive. AoE grants damage reduction, then Stealth falls off after taking the hit.",
      },
    ],
    kit: "S1 Pew, Pew, Pew!: 75% strip one; with Daydream, extra attack all enemies (25% Stun). S2 I Wanna Go Home. S3 Boom! Starlight Fall!: −1 enemy buff duration, Stun 1 turn, −30% CR, self Barrier 2 turns. Soulburn 20: those buffs +1 turn and extra turn. No anti-revive. No Seal.",
    defense: 7,
    offense: 8,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "straze",
    name: "Straze",
    short: "Straze",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["cleave", "dps", "strip"],
    tags: ["aoe", "strip", "ignore-er", "soulburn", "cr-push", "invincible"],
    effects: ["buff-dispel", "increase-cr"],
    buffs: ["Invincible"],
    uniqueEffects: [
      {
        name: "Destructive Gaze",
        text: "AoE strip all buffs. Ignores ER vs lower Attack. Damage rises as enemy count drops (≤3). Soulburn 10: −2 cooldown.",
      },
      {
        name: "Star Extinction",
        text: "AoE. Self Invincible 1 turn. Penetrates Defense of the highest-HP target. This skill cannot trigger a counterattack.",
      },
    ],
    kit: "S1 Powerful Strike: +20% CR. S2 Destructive Gaze: AoE strip all, ignore ER vs lower Attack, more damage vs fewer enemies, 3-turn CD. Soulburn 10: −2 CD. S3 Star Extinction: AoE, self Invincible 1 turn, penetrate highest-HP, no counter on this skill. 6-turn CD. Dedicated cleave closer.",
    defense: 4,
    offense: 10,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "zahhak",
    name: "Zahhak",
    short: "Zahhak",
    element: "earth",
    class: "warrior",
    tier: "A",
    roles: ["cleave", "dps"],
    tags: ["aoe", "extra-turn", "defbreak"],
    kit: "Earth cleave warrior. A reliable Rank-up tool through Champion.",
    defense: 3,
    offense: 8,
  },
  {
    id: "zio",
    name: "Zio",
    short: "Zio",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["opener", "control"],
    tags: ["stun", "extra-turn", "invincible"],
    kit: "Invincible extra-turn opener. Can steal games before the wall acts.",
    defense: 5,
    offense: 8,
  },
  {
    id: "ae-karina",
    name: "ae-KARINA",
    short: "Karina",
    element: "ice",
    class: "knight",
    tier: "A",
    roles: ["tank", "bruiser"],
    tags: ["counter", "barrier"],
    kit: "Counter knight. Holds the line in mixed bruiser defenses.",
    defense: 7,
    offense: 6,
  },
  {
    id: "peira",
    name: "Peira",
    short: "Peira",
    element: "ice",
    class: "thief",
    tier: "A",
    roles: ["opener", "strip"],
    tags: ["strip", "stun", "cr-push"],
    kit: "Covenant opener. The most common first-pick speed unit on a new account.",
    defense: 3,
    offense: 8,
  },
  {
    id: "flan",
    name: "Flan",
    short: "Flan",
    element: "ice",
    class: "ranger",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "cr-push", "defbreak"],
    kit: "Defense break plus strip. Core enabler for mid-rank cleave.",
    defense: 3,
    offense: 8,
  },
  {
    id: "landy",
    name: "Landy",
    short: "Landy",
    element: "earth",
    class: "ranger",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "counter"],
    kit: "Attack-scaling ranger. Punishes buffed teams and still cleaves.",
    defense: 4,
    offense: 7,
  },
  {
    id: "hwayoung",
    name: "Hwayoung",
    short: "Hwayoung",
    element: "fire",
    class: "warrior",
    tier: "B",
    roles: ["dps"],
    tags: ["fixed-dmg", "injury"],
    kit: "Single-target nuke. Still deletes a squishy if she takes the turn.",
    defense: 3,
    offense: 7,
  },
  {
    id: "bystander-hwayoung",
    name: "Bystander Hwayoung",
    short: "ML Hwayoung",
    element: "dark",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["fixed-dmg", "injury"],
    kit: "Dark Hwayoung. A scare pick on defense when the HP threshold is real.",
    defense: 6,
    offense: 8,
  },
  {
    id: "roana",
    name: "Roana",
    short: "Roana",
    element: "earth",
    class: "soulweaver",
    tier: "A",
    roles: ["healer"],
    tags: ["counter", "barrier"],
    kit: "Anti-counter-attack healer. Punishes extra-attack cores on defense.",
    defense: 8,
    offense: 4,
  },
  {
    id: "senya",
    name: "Senya",
    short: "Senya",
    element: "earth",
    class: "knight",
    tier: "A",
    roles: ["tank", "dps"],
    tags: ["barrier", "fixed-dmg"],
    kit: "Effect-resistance tank with a surprising S3. Gold-to-Master staple.",
    defense: 8,
    offense: 5,
  },
  {
    id: "alencia",
    name: "Alencia",
    short: "Alencia",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["bruiser", "strip"],
    tags: ["strip", "aoe", "defbreak"],
    kit: "Strip bruiser. A cheap way to answer buffed walls.",
    defense: 6,
    offense: 6,
  },
  {
    id: "destina",
    name: "Destina",
    short: "Destina",
    element: "earth",
    class: "soulweaver",
    tier: "B",
    roles: ["healer", "cleanse", "revive"],
    tags: ["aoe"],
    kit: "Full cleanse plus revive. Still a fine Master support.",
    defense: 6,
    offense: 4,
  },
  {
    id: "seaside-bellona",
    name: "Seaside Bellona",
    short: "SSB",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["dps", "bruiser"],
    tags: ["counter", "defbreak", "aoe"],
    kit: "Counter ranger. Punishes AoE and still defense-breaks.",
    defense: 7,
    offense: 6,
  },
  {
    id: "arbiter-vildred",
    name: "Arbiter Vildred",
    short: "A.Vildred",
    element: "dark",
    class: "thief",
    tier: "B",
    roles: ["cleave", "dps"],
    tags: ["aoe", "soulburn", "extra-turn"],
    kit: "The original soulburn cleave. Still farm Gold if the strip is there.",
    defense: 2,
    offense: 7,
  },
  {
    id: "specter-tenebria",
    name: "Specter Tenebria",
    short: "Spec Tene",
    element: "dark",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["unhealable", "extra-turn"],
    kit: "Unhealable plus extra turn. Deletes a key soul weaver.",
    defense: 4,
    offense: 7,
  },
  {
    id: "lionheart-cermia",
    name: "Lionheart Cermia",
    short: "LH Cermia",
    element: "light",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["fixed-dmg", "ignore-er"],
    kit: "Ignore-defense firebrand. A clean answer to fat HP knights.",
    defense: 4,
    offense: 8,
  },
  {
    id: "little-queen-charlotte",
    name: "Little Queen Charlotte",
    short: "LQ Charlotte",
    element: "light",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Light warrior cleave. Punishes Earth cores and still one-shots squishies.",
    defense: 4,
    offense: 8,
  },
  {
    id: "angel-of-light-angelica",
    name: "Angel of Light Angelica",
    short: "A.Angelica",
    element: "light",
    class: "mage",
    tier: "S",
    roles: ["control", "strip", "cleanse"],
    tags: ["strip", "silence", "cr-cut", "cr-push", "aoe", "soulburn"],
    effects: ["buff-dispel", "debuff-dispel", "decrease-cr", "increase-cr"],
    buffs: ["Skill Nullifier"],
    debuffs: ["Silence", "Cannot Buff"],
    uniqueEffects: [
      {
        name: "Guardian of Light",
        text: "Immune to Stun. After every attack an ally takes (not her), +8% Combat Readiness. On an attack that hits all allies, 75% chance to activate Guardian Angel.",
      },
      {
        name: "Guardian Angel",
        text: "Cleanses one debuff from all allies, then grants Skill Nullifier once.",
      },
      {
        name: "Skill Nullifier",
        text: "Nullifies damage from skills.",
      },
    ],
    kit: "S1 Ritualistic Touch: 50% Silence 1 turn; if silenced, −25% CR. Soulburn 10: 100% Silence. S2 Guardian of Light. S3 Judgment of Angels: AoE strip two, 70% Cannot Buff 2 turns + Silence 1 turn. Not team Immunity. Not Invincible.",
    defense: 8,
    offense: 7,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "dragon-king-sharun",
    name: "Dragon King Sharun",
    short: "DK Sharun",
    element: "light",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "control"],
    tags: ["barrier", "cr-push"],
    kit: "Light support that holds control drafts together.",
    defense: 7,
    offense: 6,
  },
  {
    id: "iseria",
    name: "Iseria",
    short: "Iseria",
    element: "earth",
    class: "ranger",
    tier: "B",
    roles: ["strip", "opener"],
    tags: ["strip", "defbreak", "unhealable"],
    kit: "The original strip. Still enables every budget cleave.",
    defense: 2,
    offense: 7,
  },
  {
    id: "tywin",
    name: "Tywin",
    short: "Tywin",
    element: "ice",
    class: "knight",
    tier: "B",
    roles: ["opener", "tank"],
    tags: ["defbreak", "cr-push", "aoe"],
    kit: "AoE defense break opener. A stepping stone to A.Tywin.",
    defense: 5,
    offense: 6,
  },
  {
    id: "operator-sigret",
    name: "Operator Sigret",
    short: "O.Sigret",
    element: "dark",
    class: "ranger",
    tier: "B",
    roles: ["dps"],
    tags: ["defbreak", "unhealable"],
    kit: "Single-target execute. Deletes the remaining knight after injury stacks.",
    defense: 3,
    offense: 7,
  },
  {
    id: "dark-corvus",
    name: "Dark Corvus",
    short: "D.Corvus",
    element: "dark",
    class: "warrior",
    tier: "B",
    roles: ["bruiser", "tank"],
    tags: ["fixed-dmg", "injury"],
    kit: "One-shot counter to glass mages. Slow, obvious, still works on defense.",
    defense: 7,
    offense: 5,
  },
  {
    id: "adventurer-ras",
    name: "Adventurer Ras",
    short: "A.Ras",
    element: "fire",
    class: "knight",
    tier: "B",
    roles: ["opener", "tank"],
    tags: ["defbreak", "immunity", "cr-push"],
    kit: "Free unit opener. Every account should have him built for Gold.",
    defense: 5,
    offense: 6,
  },
  {
    id: "astromancer-elena",
    name: "Astromancer Elena",
    short: "A.Elena",
    element: "light",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "control"],
    tags: ["cr-push", "dual-attack", "extra-turn"],
    kit: "CR and extra-attack support. Feeds dual-attack and turn-2 teams.",
    defense: 6,
    offense: 6,
  },
  {
    id: "commander-pavel",
    name: "Commander Pavel",
    short: "C.Pavel",
    element: "light",
    class: "ranger",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "ignore-er", "cr-cut"],
    kit: "AoE ranger that ignores Effect Resistance. A clean pick into bulky mages.",
    defense: 4,
    offense: 8,
  },
  {
    id: "faithless-lidica",
    name: "Faithless Lidica",
    short: "F.Lidica",
    element: "light",
    class: "ranger",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Extra attacks and CR. Takes over the first cycle if she is left open.",
    defense: 5,
    offense: 8,
  },
  {
    id: "architect-laika",
    name: "Architect Laika",
    short: "A.Laika",
    element: "light",
    class: "mage",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["extra-turn", "aoe", "dual-attack"],
    kit: "Extra-attack mage. Converts one opening into a full cycle of hits.",
    defense: 5,
    offense: 9,
  },
  {
    id: "silver-blade-aramintha",
    name: "Silver Blade Aramintha",
    short: "SB Ara",
    element: "light",
    class: "mage",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["stun", "counter", "aoe"],
    kit: "Stun mage with a counter kit. Holds mid-fight if the first AoE lands.",
    defense: 6,
    offense: 7,
  },
  {
    id: "sylvan-sage-vivian",
    name: "Sylvan Sage Vivian",
    short: "SS Vivian",
    element: "light",
    class: "mage",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["extra-turn", "aoe", "soulburn"],
    kit: "Extra-turn AoE mage. Soulburn ends the cycle if the wall is already cracked.",
    defense: 4,
    offense: 8,
  },
  {
    id: "desert-jewel-basar",
    name: "Desert Jewel Basar",
    short: "DJ Basar",
    element: "light",
    class: "soulweaver",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "cr-push", "aoe"],
    kit: "AoE strip plus CR. The classic way to open a buffed wall.",
    defense: 5,
    offense: 8,
  },
  {
    id: "lisette",
    name: "Lisette",
    short: "Lisette",
    element: "light",
    class: "soulweaver",
    tier: "S",
    roles: ["revive", "healer", "cleanse"],
    tags: ["invincible", "cr-push", "immunity", "soulburn"],
    effects: ["revive", "increase-cr", "debuff-dispel"],
    buffs: ["Increase Speed"],
    uniqueEffects: [
      {
        name: "Divinity",
        text: "Immune to debuffs. +20% Health and Defense per stack. Starts the fight with four stacks.",
      },
      {
        name: "Fragment of Life",
        text: "Immune to buffs and debuffs, nullifies all damage. Returns as the hero at the start of the second turn. Destroyed if Lisette dies.",
      },
      {
        name: "Time Reversal",
        text: "Returns allies to their start-of-battle state. PvP only. S3 also grants Increase Speed.",
      },
    ],
    kit: "S1 heals the team (HP scaling). Soulburn cleanses an ally with Divinity, pushes CR, and restores a Fragment of Life. S2: four Divinity; when an ally dies, revive them as a Fragment of Life. S3: full heal + Speed; if she has Divinity, Time Reversal on allies.",
    defense: 9,
    offense: 5,
    verified: true,
    checkedAt: "2026-08-31",
  },
  {
    id: "judge-kise",
    name: "Judge Kise",
    short: "J.Kise",
    element: "light",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack warrior. Ignores fat Defense and deletes the backline.",
    defense: 4,
    offense: 8,
  },
  {
    id: "successor-taeyou",
    name: "Successor Taeyou",
    short: "S.Taeyou",
    element: "light",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "dual-attack", "aoe"],
    kit: "Extra-turn bruiser. Turns one dual-attack into a long, messy fight.",
    defense: 7,
    offense: 8,
  },
  {
    id: "monarch-of-the-sword-iseria",
    name: "Monarch of the Sword Iseria",
    short: "MS Iseria",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["injury", "counter", "cr-push"],
    kit: "Injury knight on a counter kit. Punishes hits and stacks the long fight.",
    defense: 8,
    offense: 8,
  },
  {
    id: "specimen-sez",
    name: "Specimen Sez",
    short: "S.Sez",
    element: "light",
    class: "thief",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Extra-attack thief. Finishes low-HP units after the first cut.",
    defense: 4,
    offense: 8,
  },
  {
    id: "twisted-eidolon-kayron",
    name: "Twisted Eidolon Kayron",
    short: "TE Kayron",
    element: "light",
    class: "thief",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["counter", "extra-turn", "unhealable"],
    kit: "Counter thief. Lives the first hit, then takes extra turns and shuts down heals.",
    defense: 7,
    offense: 9,
  },
  {
    id: "designer-lilibet",
    name: "Designer Lilibet",
    short: "D.Lilibet",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["unhealable", "ignore-er", "extra-turn"],
    kit: "Extra-attack warrior. Lands unhealable through Effect Resistance — a clean evasion answer.",
    defense: 6,
    offense: 9,
  },
  {
    id: "disciplinary-prefect-aria",
    name: "Disciplinary Prefect Aria",
    short: "DP Aria",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "tank"],
    tags: ["injury", "extra-turn", "cr-push"],
    kit: "HP-scaling injury bruiser. Extra attacks stack the long fight.",
    defense: 8,
    offense: 8,
  },
  {
    id: "lone-crescent-bellona",
    name: "Lone Crescent Bellona",
    short: "LC Bellona",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["aoe", "immunity", "cr-push"],
    kit: "Crit warrior. Builds fighting spirit, then AoE and CR on the extra cycle.",
    defense: 6,
    offense: 9,
  },
  {
    id: "martial-artist-ken",
    name: "Martial Artist Ken",
    short: "MA Ken",
    element: "dark",
    class: "warrior",
    tier: "A",
    roles: ["bruiser", "dps"],
    tags: ["counter", "stun"],
    kit: "Counter bruiser. Stuns on the bounce and wins ugly 1v1s.",
    defense: 8,
    offense: 7,
  },
  {
    id: "salome",
    name: "Salome",
    short: "Salome",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["control", "bruiser"],
    tags: ["dual-attack", "seal", "extra-turn"],
    kit: "Control warrior. Clones a skill and turns the fight into her script.",
    defense: 7,
    offense: 8,
  },
  {
    id: "rhianna-and-luciella",
    name: "Rhianna and Luciella",
    short: "R&L",
    element: "dark",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Extra-attack thief. Two bodies, one cycle — CR and hits stack fast.",
    defense: 5,
    offense: 8,
  },
  {
    id: "hellion-lua",
    name: "Hellion Lua",
    short: "H.Lua",
    element: "dark",
    class: "ranger",
    tier: "S",
    roles: ["control", "tank"],
    tags: ["provoke", "cr-push", "counter", "ignore-er"],
    kit: "AoE provoke that ignores Effect Resistance. Allies counter after she is hit.",
    defense: 8,
    offense: 6,
  },
  {
    id: "ainz-ooal-gown",
    name: "Ainz Ooal Gown",
    short: "Ainz",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["unhealable", "aoe", "extra-turn"],
    kit: "AoE mage. Unhealable plus extra attacks if the first cycle lands.",
    defense: 5,
    offense: 8,
  },
  {
    id: "archdemons-shadow",
    name: "Archdemon's Shadow",
    short: "ADS",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Extra-turn control mage. Steals the cycle after the first skill.",
    defense: 5,
    offense: 8,
  },
  {
    id: "tidal-rift-elvira",
    name: "Tidal Rift Elvira",
    short: "TR Elvira",
    element: "dark",
    class: "mage",
    tier: "S",
    roles: ["control", "dps"],
    tags: ["seal", "cr-push", "aoe"],
    kit: "Seal and curse mage. Extra attacks absorb HP and scramble CR.",
    defense: 6,
    offense: 9,
  },
  {
    id: "top-model-luluca",
    name: "Top Model Luluca",
    short: "TM Lulu",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["extra-turn", "cr-cut", "aoe"],
    kit: "Extra-turn mage. Cuts CR and takes a second skill in the same cycle.",
    defense: 5,
    offense: 8,
  },
  {
    id: "arunka",
    name: "Arunka",
    short: "Arunka",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["injury", "extra-turn", "aoe"],
    kit: "Injury warrior. Extra attacks stack the long fight and ignore fat HP.",
    defense: 7,
    offense: 8,
  },
  {
    id: "immortal-wukong",
    name: "Immortal Wukong",
    short: "Wukong",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "tank"],
    tags: ["barrier", "extra-turn", "invincible"],
    kit: "Bruiser who refuses to stay down. Lives the first cycle, then takes extra turns.",
    defense: 8,
    offense: 8,
  },
  {
    id: "laia",
    name: "Laia",
    short: "Laia",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["control", "bruiser"],
    tags: ["dual-attack", "cr-push", "extra-turn"],
    kit: "Dual-attack engine. Feeds the team extra hits and CR.",
    defense: 6,
    offense: 7,
  },
  {
    id: "lilibet",
    name: "Lilibet",
    short: "Lilibet",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["dps"],
    tags: ["unhealable", "extra-turn"],
    kit: "Unhealable extra attacks. Niche, still useful into sustain walls.",
    defense: 4,
    offense: 7,
  },
  {
    id: "mui",
    name: "Mui",
    short: "Mui",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["control", "opener"],
    tags: ["stun", "cr-push", "aoe"],
    kit: "AoE stun opener. Old, but still drafts when the wall is slow.",
    defense: 4,
    offense: 7,
  },
  {
    id: "rimuru",
    name: "Rimuru",
    short: "Rimuru",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["control", "dps"],
    tags: ["extra-turn", "aoe", "strip"],
    kit: "Extra-turn collab warrior. Copies a skill and takes over the cycle.",
    defense: 6,
    offense: 8,
  },
  {
    id: "yufine",
    name: "Yufine",
    short: "Yufine",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["stun", "aoe"],
    kit: "AoE stun warrior. Simple closer if the wall is already cracked.",
    defense: 4,
    offense: 7,
  },
  {
    id: "albedo",
    name: "Albedo",
    short: "Albedo",
    element: "earth",
    class: "knight",
    tier: "A",
    roles: ["tank", "bruiser"],
    tags: ["barrier", "provoke"],
    kit: "Barrier knight. Holds the front while the rest of the draft works.",
    defense: 8,
    offense: 5,
  },
  {
    id: "charles",
    name: "Charles",
    short: "Charles",
    element: "earth",
    class: "knight",
    tier: "A",
    roles: ["dps", "tank"],
    tags: ["dual-attack", "extra-turn", "aoe"],
    kit: "Dual-attack knight. Extra hits on counter and on the S3.",
    defense: 7,
    offense: 7,
  },
  {
    id: "estelle",
    name: "Estelle",
    short: "Estelle",
    element: "earth",
    class: "knight",
    tier: "A",
    roles: ["tank", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "CR knight. Extra turns and a frontline that still pushes the team.",
    defense: 7,
    offense: 6,
  },
  {
    id: "yulha",
    name: "Yulha",
    short: "Yulha",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["dps", "bruiser"],
    tags: ["stun", "extra-turn"],
    kit: "Stun warrior. Older kit, still fills a bruiser slot.",
    defense: 5,
    offense: 7,
  },
  {
    id: "baiken",
    name: "Baiken",
    short: "Baiken",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["dps"],
    tags: ["extra-turn", "counter", "unhealable"],
    kit: "Extra-attack warrior. Punishes a miss and shuts down heals.",
    defense: 5,
    offense: 8,
  },
  {
    id: "blooming-lidica",
    name: "Blooming Lidica",
    short: "B.Lidica",
    element: "earth",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "cr-push"],
    kit: "Speed thief. Gains turns as the fight goes and never lets the wall cycle.",
    defense: 4,
    offense: 8,
  },
  {
    id: "ram",
    name: "Ram",
    short: "Ram",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["aoe", "extra-turn"],
    kit: "Collab AoE mage. Extra attacks if the first skill lands.",
    defense: 4,
    offense: 7,
  },
  {
    id: "vivian",
    name: "Vivian",
    short: "Vivian",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["immunity", "aoe", "extra-turn"],
    kit: "Immunity AoE mage. Old cleave piece that still works in Gold.",
    defense: 4,
    offense: 7,
  },
  {
    id: "ocean-breeze-luluca",
    name: "Ocean Breeze Luluca",
    short: "OB Lulu",
    element: "earth",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["barrier", "cr-push"],
    kit: "Barrier soul weaver. Keeps the bruiser alive through the first AoE.",
    defense: 7,
    offense: 5,
  },
  {
    id: "ray",
    name: "Ray",
    short: "Ray",
    element: "earth",
    class: "soulweaver",
    tier: "B",
    roles: ["healer", "cleanse"],
    tags: ["unhealable", "aoe"],
    kit: "Cleanse plus unhealable. Utility soul weaver for long fights.",
    defense: 6,
    offense: 5,
  },
  {
    id: "young-senya",
    name: "Young Senya",
    short: "Y.Senya",
    element: "earth",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "CR soul weaver. Extra turns and a push that starts the team's cycle.",
    defense: 7,
    offense: 6,
  },
  {
    id: "celine",
    name: "Celine",
    short: "Celine",
    element: "earth",
    class: "thief",
    tier: "B",
    roles: ["dps", "evasion"],
    tags: ["evade", "extra-turn", "counter"],
    kit: "Evasion extra-attack thief. Punishes a single-target S3.",
    defense: 6,
    offense: 7,
  },
  {
    id: "ervalen",
    name: "Ervalen",
    short: "Ervalen",
    element: "earth",
    class: "thief",
    tier: "B",
    roles: ["dps"],
    tags: ["defbreak", "extra-turn"],
    kit: "Def-break extra attacks. A simple closer if someone else opens.",
    defense: 4,
    offense: 7,
  },
  {
    id: "midnight-gala-lilias",
    name: "Midnight Gala Lilias",
    short: "MG Lilias",
    element: "earth",
    class: "thief",
    tier: "S",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "ignore-er"],
    kit: "Limited assassin. Extra attacks that ignore Effect Resistance.",
    defense: 4,
    offense: 9,
  },
  {
    id: "vildred",
    name: "Vildred",
    short: "Vildred",
    element: "earth",
    class: "thief",
    tier: "B",
    roles: ["cleave", "dps"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE extra-attack thief. Classic Gold cleave.",
    defense: 3,
    offense: 7,
  },
  {
    id: "violet",
    name: "Violet",
    short: "Violet",
    element: "earth",
    class: "thief",
    tier: "A",
    roles: ["evasion", "dps"],
    tags: ["evade", "extra-turn", "counter"],
    kit: "Evasion thief. Misses eat the draft, extra attacks finish the rest.",
    defense: 7,
    offense: 7,
  },
  {
    id: "bellona",
    name: "Bellona",
    short: "Bellona",
    element: "earth",
    class: "ranger",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "defbreak"],
    kit: "AoE def-break ranger. Old, still a clean PvE and low-ladder closer.",
    defense: 4,
    offense: 7,
  },
  {
    id: "command-model-laika",
    name: "Command Model Laika",
    short: "CM Laika",
    element: "earth",
    class: "ranger",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["cr-push", "seal"],
    kit: "Target lock ranger. Forces the wall to look at her, then extra attacks.",
    defense: 5,
    offense: 8,
  },
  {
    id: "fenris",
    name: "Fenris",
    short: "Fenris",
    element: "earth",
    class: "ranger",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe", "injury"],
    kit: "Extra-attack ranger. Bruiser-shaped damage that still hits AoE.",
    defense: 6,
    offense: 9,
  },
  {
    id: "pavel",
    name: "Pavel",
    short: "Pavel",
    element: "earth",
    class: "ranger",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "ignore-er", "extra-turn"],
    kit: "Ignore-ER AoE ranger. Soulburn ends a cracked wall.",
    defense: 3,
    offense: 8,
  },
  {
    id: "saria",
    name: "Saria",
    short: "Saria",
    element: "earth",
    class: "ranger",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["cr-push", "aoe", "extra-turn"],
    kit: "CR ranger. Extra attacks and a push that starts the team's cycle.",
    defense: 5,
    offense: 8,
  },
  {
    id: "ae-giselle",
    name: "ae-GISELLE",
    short: "ae-GISELLE",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["aoe", "extra-turn", "cr-cut"],
    kit: "Collab AoE mage. Extra turn if the first skill lands.",
    defense: 4,
    offense: 7,
  },
  {
    id: "basar",
    name: "Basar",
    short: "Basar",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["strip", "opener"],
    tags: ["strip", "stun", "aoe"],
    kit: "AoE strip plus stun. The classic way to open a buffed wall.",
    defense: 4,
    offense: 8,
  },
  {
    id: "eye-of-the-abyss-fumyr",
    name: "Eye of the Abyss Fumyr",
    short: "EotA Fumyr",
    element: "earth",
    class: "mage",
    tier: "S",
    roles: ["control", "dps"],
    tags: ["extra-turn", "cr-cut", "seal"],
    kit: "Control mage. Extra turns and a lock that steals the mid-fight.",
    defense: 6,
    offense: 8,
  },
  {
    id: "ludwig",
    name: "Ludwig",
    short: "Ludwig",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["cleave", "dps"],
    tags: ["aoe", "soulburn", "invincible"],
    kit: "Soulburn AoE mage. Invincible window, then the wall has to be dead.",
    defense: 3,
    offense: 8,
  },
  {
    id: "chloe",
    name: "Chloe",
    short: "Chloe",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Extra-attack warrior. AoE closer if the wall is already cracked.",
    defense: 4,
    offense: 8,
  },
  {
    id: "lethe",
    name: "Lethe",
    short: "Lethe",
    element: "ice",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "unhealable", "cr-push"],
    kit: "Limited bruiser. Extra attacks, then extinction if the omen stacks.",
    defense: 7,
    offense: 8,
  },
  {
    id: "luna",
    name: "Luna",
    short: "Luna",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["defbreak", "extra-turn"],
    kit: "Def-break extra attacks. A clean closer after the opener.",
    defense: 5,
    offense: 8,
  },
  {
    id: "rem",
    name: "Rem",
    short: "Rem",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "stun", "extra-turn"],
    kit: "AoE stun warrior. Extra attacks if the first cycle lands.",
    defense: 5,
    offense: 8,
  },
  {
    id: "sigret",
    name: "Sigret",
    short: "Sigret",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["dps"],
    tags: ["unhealable", "extra-turn"],
    kit: "Unhealable extra attacks. Punishes sustain walls in a short fight.",
    defense: 4,
    offense: 8,
  },
  {
    id: "taeyou",
    name: "Taeyou",
    short: "Taeyou",
    element: "ice",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "dual-attack", "aoe"],
    kit: "Extra-turn warrior. Dual attacks turn one opening into a full cycle.",
    defense: 6,
    offense: 9,
  },
  {
    id: "brieg",
    name: "Brieg",
    short: "Brieg",
    element: "ice",
    class: "knight",
    tier: "A",
    roles: ["tank", "bruiser"],
    tags: ["barrier", "cr-push"],
    kit: "Barrier knight. Holds the front and still pushes the team.",
    defense: 8,
    offense: 6,
  },
  {
    id: "summer-break-charlotte",
    name: "Summer Break Charlotte",
    short: "SB Charlotte",
    element: "ice",
    class: "knight",
    tier: "A",
    roles: ["tank", "dps"],
    tags: ["aoe", "extra-turn", "barrier"],
    kit: "Limited knight. Extra attacks off a fat frontline.",
    defense: 7,
    offense: 7,
  },
  {
    id: "argent-waves-hwayoung",
    name: "Argent Waves Hwayoung",
    short: "AW Hwayoung",
    element: "ice",
    class: "thief",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["extra-turn", "aoe", "strip"],
    kit: "Limited thief. Extra attacks after a non-attack skill, then AoE.",
    defense: 4,
    offense: 9,
  },
  {
    id: "elvira",
    name: "Elvira",
    short: "Elvira",
    element: "ice",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "cr-push"],
    kit: "Extra-attack thief. Takes the cycle if she is left open.",
    defense: 4,
    offense: 8,
  },
  {
    id: "kise",
    name: "Kise",
    short: "Kise",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE ranger. Old cleave piece that still works in Gold.",
    defense: 3,
    offense: 7,
  },
  {
    id: "sez",
    name: "Sez",
    short: "Sez",
    element: "ice",
    class: "thief",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Extra-attack thief. Finishes low-HP units after the first cut.",
    defense: 3,
    offense: 7,
  },
  {
    id: "birgitta",
    name: "Birgitta",
    short: "Birgitta",
    element: "ice",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "barrier", "immunity"],
    kit: "CR soul weaver. Immunity window plus a push that starts the cycle.",
    defense: 8,
    offense: 6,
  },
  {
    id: "emilia",
    name: "Emilia",
    short: "Emilia",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "cr-push"],
    kit: "Cleanse plus immunity. Keeps the bruiser alive through the first AoE.",
    defense: 7,
    offense: 5,
  },
  {
    id: "fenne",
    name: "Fenne",
    short: "Fenne",
    element: "ice",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "CR soul weaver. Extra turns and a push that owns the mid-fight.",
    defense: 7,
    offense: 6,
  },
  {
    id: "frida",
    name: "Frida",
    short: "Frida",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "cr-push"],
    kit: "Team immunity soul weaver. The clean way to enter a control fight.",
    defense: 7,
    offense: 5,
  },
  {
    id: "tactical-archetype-coli",
    name: "Tactical Archetype Coli",
    short: "TA Coli",
    element: "ice",
    class: "thief",
    tier: "S",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "cr-push"],
    kit: "Extra-attack thief. Data-driven cycle steal — speed contest or die.",
    defense: 4,
    offense: 9,
  },
  {
    id: "aubade-ludwig",
    name: "Aubade Ludwig",
    short: "Aubade",
    element: "ice",
    class: "ranger",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn", "soulburn"],
    kit: "Limited ranger. Extra attacks then a soulburn that ends the cycle.",
    defense: 4,
    offense: 9,
  },
  {
    id: "aube",
    name: "Aube",
    short: "Aube",
    element: "ice",
    class: "ranger",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Limited ranger. Extra attacks and a CR push that starts the team's cycle.",
    defense: 5,
    offense: 8,
  },
  {
    id: "byblis",
    name: "Byblis",
    short: "Byblis",
    element: "ice",
    class: "ranger",
    tier: "A",
    roles: ["opener", "control"],
    tags: ["defbreak", "cr-push", "aoe"],
    kit: "Limited speed ranger. Contest turn one, def-break, cut buff duration.",
    defense: 4,
    offense: 8,
  },
  {
    id: "cerise",
    name: "Cerise",
    short: "Cerise",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["opener", "control"],
    tags: ["cr-cut", "unhealable", "aoe"],
    kit: "AoE CR-cut opener. Old, still drafts into greedy speed teams.",
    defense: 4,
    offense: 7,
  },
  {
    id: "lua",
    name: "Lua",
    short: "Lua",
    element: "ice",
    class: "ranger",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "stun", "cr-push"],
    kit: "Strip plus stun. The opener when B.Iseria is not in the draft.",
    defense: 4,
    offense: 8,
  },
  {
    id: "riza-hawkeye",
    name: "Riza Hawkeye",
    short: "Riza",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["dps"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack ranger. Collab closer if the wall is already open.",
    defense: 4,
    offense: 7,
  },
  {
    id: "yuna",
    name: "Yuna",
    short: "Yuna",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "cr-push"],
    kit: "AoE ranger. CR push plus damage — old PvE staple.",
    defense: 4,
    offense: 7,
  },
  {
    id: "aria",
    name: "Aria",
    short: "Aria",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["control", "tank"],
    tags: ["counter", "barrier", "aoe"],
    kit: "Counter mage. Fat, slow, and painful if you hit her.",
    defense: 7,
    offense: 6,
  },
  {
    id: "dizzy",
    name: "Dizzy",
    short: "Dizzy",
    element: "ice",
    class: "mage",
    tier: "A",
    roles: ["control"],
    tags: ["cr-cut", "unhealable", "aoe"],
    kit: "AoE control mage. CR lock plus unhealable — the fight gets slow.",
    defense: 6,
    offense: 6,
  },
  {
    id: "eda",
    name: "Eda",
    short: "Eda",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["aoe", "stun", "extra-turn"],
    kit: "AoE stun mage. Extra attacks if the first skill lands.",
    defense: 4,
    offense: 7,
  },
  {
    id: "fairytale-tenebria",
    name: "Fairytale Tenebria",
    short: "FT Tene",
    element: "ice",
    class: "mage",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["stun", "extra-turn", "aoe"],
    kit: "Stun extra-turn mage. Takes over the cycle after the first skill.",
    defense: 5,
    offense: 8,
  },
  {
    id: "fern",
    name: "Fern",
    short: "Fern",
    element: "ice",
    class: "mage",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn", "ignore-er"],
    kit: "Extra-attack mage. Ignore-ER closer if the wall is already stripped.",
    defense: 4,
    offense: 9,
  },
  {
    id: "fumyr",
    name: "Fumyr",
    short: "Fumyr",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["control", "dps"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-turn mage. Older kit — still fills a control slot.",
    defense: 5,
    offense: 7,
  },
  {
    id: "luluca",
    name: "Luluca",
    short: "Luluca",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["defbreak", "aoe"],
    kit: "Def-break mage. Simple enabler for a cleave.",
    defense: 4,
    offense: 7,
  },
  {
    id: "zeno",
    name: "Zeno",
    short: "Zeno",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["dps"],
    tags: ["aoe", "extra-turn"],
    kit: "HP-scaling AoE mage. Niche, still a closer if he lives.",
    defense: 5,
    offense: 7,
  },
  {
    id: "abigail",
    name: "Abigail",
    short: "Abigail",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "injury", "aoe"],
    kit: "Injury bruiser. Extra attacks stack the long fight.",
    defense: 7,
    offense: 8,
  },
  {
    id: "aki",
    name: "Aki",
    short: "Aki",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack warrior. Converts one opening into a full cycle of hits.",
    defense: 6,
    offense: 9,
  },
  {
    id: "benimaru",
    name: "Benimaru",
    short: "Benimaru",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE extra-attack warrior. Collab closer if the wall is already cracked.",
    defense: 5,
    offense: 8,
  },
  {
    id: "cermia",
    name: "Cermia",
    short: "Cermia",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["dps"],
    tags: ["extra-turn", "ignore-er"],
    kit: "Single-target extra attacks. Ignores ER and deletes the threat unit.",
    defense: 4,
    offense: 8,
  },
  {
    id: "edward-elric",
    name: "Edward Elric",
    short: "Edward",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack warrior. Collab bruiser that still hits AoE.",
    defense: 6,
    offense: 8,
  },
  {
    id: "guard-captain-krau",
    name: "Guard Captain Krau",
    short: "GC Krau",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["bruiser", "tank"],
    tags: ["barrier", "extra-turn", "aoe"],
    kit: "Limited bruiser. Lives the first cycle, then extra attacks.",
    defense: 8,
    offense: 7,
  },
  {
    id: "holiday-yufine",
    name: "Holiday Yufine",
    short: "H.Yufine",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["aoe", "stun", "extra-turn"],
    kit: "Limited AoE warrior. Stun plus extra attacks — a clean summer closer.",
    defense: 5,
    offense: 9,
  },
  {
    id: "jack-o",
    name: "Jack-O'",
    short: "Jack-O'",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["stun", "extra-turn", "dual-attack"],
    kit: "Stun warrior. Extra attacks and a dual-attack engine for the backline.",
    defense: 5,
    offense: 8,
  },
  {
    id: "kane",
    name: "Kane",
    short: "Kane",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe", "unhealable"],
    kit: "Extra-attack warrior. Unhealable closer that still lives a hit.",
    defense: 6,
    offense: 9,
  },
  {
    id: "ken",
    name: "Ken",
    short: "Ken",
    element: "fire",
    class: "warrior",
    tier: "B",
    roles: ["bruiser", "dps"],
    tags: ["counter", "defbreak"],
    kit: "Counter bruiser. Old, still wins ugly 1v1s.",
    defense: 7,
    offense: 6,
  },
  {
    id: "ravi",
    name: "Ravi",
    short: "Ravi",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["bruiser", "dps"],
    tags: ["counter", "extra-turn"],
    kit: "Counter bruiser. Fighting spirit into extra attacks.",
    defense: 7,
    offense: 7,
  },
  {
    id: "sol",
    name: "Sol",
    short: "Sol",
    element: "fire",
    class: "warrior",
    tier: "B",
    roles: ["dps"],
    tags: ["extra-turn", "defbreak"],
    kit: "Extra-attack warrior. Def-break closer if someone else opens.",
    defense: 4,
    offense: 7,
  },
  {
    id: "stark",
    name: "Stark",
    short: "Stark",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe", "barrier"],
    kit: "Collab extra-attack warrior. Barrier, then a cycle of hits.",
    defense: 6,
    offense: 9,
  },
  {
    id: "cecilia",
    name: "Cecilia",
    short: "Cecilia",
    element: "fire",
    class: "knight",
    tier: "B",
    roles: ["tank", "opener"],
    tags: ["provoke", "defbreak", "aoe"],
    kit: "AoE provoke knight. Old opener that still works in Gold.",
    defense: 7,
    offense: 5,
  },
  {
    id: "charlotte",
    name: "Charlotte",
    short: "Charlotte",
    element: "fire",
    class: "knight",
    tier: "A",
    roles: ["dps", "tank"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE knight. Extra attacks off a fat frontline.",
    defense: 6,
    offense: 7,
  },
  {
    id: "ilynav",
    name: "Ilynav",
    short: "Ilynav",
    element: "fire",
    class: "knight",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "injury", "aoe"],
    kit: "Injury knight. Extra attacks that stack the long fight.",
    defense: 7,
    offense: 8,
  },
  {
    id: "ae-winter",
    name: "ae-WINTER",
    short: "ae-WINTER",
    element: "fire",
    class: "thief",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Limited AoE thief. Extra attacks if the first skill lands.",
    defense: 4,
    offense: 8,
  },
  {
    id: "haste",
    name: "Haste",
    short: "Haste",
    element: "fire",
    class: "soulweaver",
    tier: "B",
    roles: ["healer", "dps"],
    tags: ["unhealable", "aoe"],
    kit: "Unhealable soul weaver. Heals, then shuts down the wall’s sustain.",
    defense: 5,
    offense: 6,
  },
  {
    id: "kayron",
    name: "Kayron",
    short: "Kayron",
    element: "fire",
    class: "thief",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "unhealable", "invincible"],
    kit: "Extinction thief. Invincible window, then extra attacks.",
    defense: 6,
    offense: 8,
  },
  {
    id: "swift-flagbearer-sigret",
    name: "Swift Flagbearer Sigret",
    short: "SF Sigret",
    element: "fire",
    class: "thief",
    tier: "S",
    roles: ["control", "opener"],
    tags: ["strip", "silence", "dual-attack"],
    kit: "Limited thief. Strip, target lock, then the team basic-attacks.",
    defense: 5,
    offense: 8,
  },
  {
    id: "tori",
    name: "Tori",
    short: "Tori",
    element: "fire",
    class: "thief",
    tier: "S",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "cr-push"],
    kit: "Extra-attack thief. Speed contest, then the cycle is hers.",
    defense: 4,
    offense: 9,
  },
  {
    id: "afternoon-soak-flan",
    name: "Afternoon Soak Flan",
    short: "AS Flan",
    element: "fire",
    class: "ranger",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn", "ignore-er"],
    kit: "Limited ranger. Ignore-ER extra attacks that end a cracked wall.",
    defense: 4,
    offense: 9,
  },
  {
    id: "beehoo",
    name: "Beehoo",
    short: "Beehoo",
    element: "fire",
    class: "ranger",
    tier: "B",
    roles: ["dps"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack ranger. Niche, still a closer if he lives.",
    defense: 4,
    offense: 7,
  },
  {
    id: "bomb-model-kanna",
    name: "Bomb Model Kanna",
    short: "BM Kanna",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE extra-attack ranger. Bomb kit — the wall has to be dead after S3.",
    defense: 4,
    offense: 8,
  },
  {
    id: "elphelt",
    name: "Elphelt",
    short: "Elphelt",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["stun", "extra-turn", "aoe"],
    kit: "Stun ranger. Extra attacks if the first skill lands.",
    defense: 4,
    offense: 8,
  },
  {
    id: "lidica",
    name: "Lidica",
    short: "Lidica",
    element: "fire",
    class: "ranger",
    tier: "B",
    roles: ["opener", "control"],
    tags: ["cr-cut", "unhealable"],
    kit: "CR-cut opener. Old, still drafts into greedy speed teams.",
    defense: 4,
    offense: 7,
  },
  {
    id: "robin",
    name: "Robin",
    short: "Robin",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Extra-attack ranger. CR push that starts the team’s cycle.",
    defense: 5,
    offense: 8,
  },
  {
    id: "ruiza",
    name: "Ruiza",
    short: "Ruiza",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "cr-push"],
    kit: "Extra-attack ranger. Takes the cycle if she is left open.",
    defense: 4,
    offense: 8,
  },
  {
    id: "summertime-iseria",
    name: "Summertime Iseria",
    short: "ST Iseria",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "defbreak", "aoe"],
    kit: "Limited strip ranger. Def-break plus strip — a clean summer opener.",
    defense: 4,
    offense: 8,
  },
  {
    id: "aramintha",
    name: "Aramintha",
    short: "Ara",
    element: "fire",
    class: "mage",
    tier: "B",
    roles: ["control", "dps"],
    tags: ["stun", "aoe", "unhealable"],
    kit: "AoE stun mage. Old, still a Gold control piece.",
    defense: 4,
    offense: 7,
  },
  {
    id: "baal-and-sezan",
    name: "Baal & Sezan",
    short: "B&S",
    element: "fire",
    class: "mage",
    tier: "B",
    roles: ["control", "dps"],
    tags: ["aoe", "stun"],
    kit: "AoE stun mage. Simple control if the wall is slow.",
    defense: 4,
    offense: 6,
  },
  {
    id: "festive-eda",
    name: "Festive Eda",
    short: "F.Eda",
    element: "fire",
    class: "mage",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Limited AoE mage. Extra attacks that end a cracked wall.",
    defense: 4,
    offense: 8,
  },
  {
    id: "kawerik",
    name: "Kawerik",
    short: "Kawerik",
    element: "fire",
    class: "mage",
    tier: "B",
    roles: ["strip", "dps"],
    tags: ["strip", "aoe"],
    kit: "AoE strip mage. Opens a buffed wall, then the closer finishes.",
    defense: 4,
    offense: 7,
  },
  {
    id: "melissa",
    name: "Melissa",
    short: "Melissa",
    element: "fire",
    class: "mage",
    tier: "A",
    roles: ["dps"],
    tags: ["extra-turn", "unhealable"],
    kit: "Extra-turn mage. Unhealable single-target — deletes the soul weaver.",
    defense: 4,
    offense: 8,
  },
  {
    id: "tenebria",
    name: "Tenebria",
    short: "Tenebria",
    element: "fire",
    class: "mage",
    tier: "B",
    roles: ["control", "dps"],
    tags: ["stun", "aoe"],
    kit: "AoE stun mage. Sleep plus stun — old control that still works.",
    defense: 4,
    offense: 7,
  },
  {
    id: "ae-ningning",
    name: "ae-NINGNING",
    short: "ae-NINGNING",
    element: "fire",
    class: "soulweaver",
    tier: "B",
    roles: ["healer", "cleanse"],
    tags: ["barrier", "cr-push"],
    kit: "Limited soul weaver. Barrier plus a push for the team.",
    defense: 6,
    offense: 5,
  },
  {
    id: "aram",
    name: "Aram",
    short: "Aram",
    element: "fire",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "CR soul weaver. Extra turns and a push that owns the mid-fight.",
    defense: 7,
    offense: 6,
  },
  {
    id: "ivana",
    name: "Ivana",
    short: "Ivana",
    element: "fire",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "unhealable", "barrier"],
    kit: "Anti-immortal soul weaver. Punishes revive and extinction walls.",
    defense: 7,
    offense: 6,
  },
  {
    id: "perfumer-byblis",
    name: "Perfumer Byblis",
    short: "P.Byblis",
    element: "fire",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "Limited soul weaver. Extra turns and a push that starts the cycle.",
    defense: 7,
    offense: 6,
  },
  {
    id: "shuna",
    name: "Shuna",
    short: "Shuna",
    element: "fire",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "barrier"],
    kit: "Collab soul weaver. Immunity window plus sustain.",
    defense: 7,
    offense: 5,
  },
  {
    id: "tamarinne",
    name: "Tamarinne",
    short: "Tama",
    element: "fire",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["cr-push", "immunity"],
    kit: "CR soul weaver. Idol form pushes the whole team.",
    defense: 6,
    offense: 5,
  },
];

export const HERO_BY_ID: Record<string, Hero> = Object.fromEntries(
  HEROES.map((h) => [h.id, h]),
);

export function getHero(id: string): Hero | undefined {
  return HERO_BY_ID[id];
}

export const ELEMENT_LABEL: Record<Hero["element"], string> = {
  fire: "Fire",
  ice: "Ice",
  earth: "Earth",
  light: "Light",
  dark: "Dark",
};

export const CLASS_LABEL: Record<Hero["class"], string> = {
  knight: "Knight",
  warrior: "Warrior",
  mage: "Mage",
  ranger: "Ranger",
  thief: "Thief",
  soulweaver: "Soul Weaver",
};

export const TIER_ORDER: Record<Hero["tier"], number> = {
  SS: 4,
  S: 3,
  A: 2,
  B: 1,
};

export const SAMPLE_ROSTER = [
  "boss-arunka",
  "empyrean-ilynav",
  "lady-of-the-scales",
  "rinak",
  "ruele-of-light",
  "harsetti",
  "briar-witch-iseria",
  "school-nurse-yulha",
  "new-moon-luna",
  "ambitious-tywin",
  "belian",
  "blood-moon-haste",
  "conqueror-lilias",
  "dragon-bride-senya",
  "fallen-cecilia",
  "frieren",
  "genesis-ras",
  "lone-wolf-peira",
  "last-rider-krau",
  "sea-phantom-politis",
  "setsuka",
  "navy-captain-landy",
  "remnant-violet",
  "ran",
  "apocalypse-ravi",
  "maid-chloe",
  "pirate-captain-flan",
  "straze",
  "zio",
  "zahhak",
  "mort",
  "krau",
  "diene",
  "solitaria",
  "milim",
  "mediator-kawerik",
  "flan",
  "peira",
  "landy",
  "roana",
  "senya",
  "lionheart-cermia",
  "hecate",
  "urban-shadow-choux",
] as const;

export const STARTER_ROSTER = [
  "adventurer-ras",
  "peira",
  "iseria",
  "flan",
  "straze",
  "zahhak",
  "milim",
  "diene",
  "krau",
  "senya",
  "fallen-cecilia",
  "ruele-of-light",
  "belian",
  "ran",
  "landy",
  "choux",
  "seaside-bellona",
  "tywin",
  "destina",
  "alencia",
  "apocalypse-ravi",
  "remnant-violet",
  "ambitious-tywin",
  "last-rider-krau",
] as const;
