import type { Hero } from "./types";

export const HEROES: Hero[] = [
  {
    id: "boss-arunka",
    name: "Boss Arunka",
    short: "B.Arunka",
    element: "light",
    class: "knight",
    tier: "SS",
    roles: ["bruiser", "dps"],
    tags: ["injury", "barrier", "aoe"],
    kit: "Threat multiplier. Scales damage and becomes a problem if she is not locked down before her cycle.",
    defense: 10,
    offense: 9,
  },
  {
    id: "empyrean-ilynav",
    name: "Empyrean Ilynav",
    short: "E.Ilynav",
    element: "light",
    class: "knight",
    tier: "SS",
    roles: ["bruiser", "tank"],
    tags: ["injury", "counter", "extra-turn"],
    kit: "Injury bruiser who wins long 1v1s. Core answer to speed-capped stalls.",
    defense: 9,
    offense: 9,
  },
  {
    id: "lady-of-the-scales",
    name: "Lady of the Scales",
    short: "Scales",
    element: "light",
    class: "soulweaver",
    tier: "SS",
    roles: ["control", "healer"],
    tags: ["cr-cut", "silence", "barrier"],
    kit: "Dictates pacing. Turns the fight into her tempo and punishes greedy openers.",
    defense: 9,
    offense: 8,
  },
  {
    id: "new-moon-luna",
    name: "New Moon Luna",
    short: "NM Luna",
    element: "light",
    class: "mage",
    tier: "SS",
    roles: ["bruiser", "dps"],
    tags: ["injury", "aoe"],
    kit: "High ceiling against fat HP walls. Wants a long, bruiser-shaped fight.",
    defense: 8,
    offense: 9,
  },
  {
    id: "rinak",
    name: "Rinak",
    short: "Rinak",
    element: "earth",
    class: "thief",
    tier: "SS",
    roles: ["control", "opener"],
    tags: ["cr-cut", "cr-push", "seal"],
    kit: "Scrambles turn order. Speed-stacked cleaves lose their script against her.",
    defense: 8,
    offense: 9,
  },
  {
    id: "ruele-of-light",
    name: "Ruele of Light",
    short: "Ruele",
    element: "light",
    class: "soulweaver",
    tier: "SS",
    roles: ["revive", "healer"],
    tags: ["invincible", "barrier"],
    kit: "The revive that makes walls sticky. Ban or bring anti-revive, or the fight resets.",
    defense: 10,
    offense: 5,
  },
  {
    id: "school-nurse-yulha",
    name: "School Nurse Yulha",
    short: "SN Yulha",
    element: "dark",
    class: "thief",
    tier: "SS",
    roles: ["healer", "cleanse", "bruiser"],
    tags: ["counter", "barrier"],
    kit: "Shuts down aggro cleave with sustain and awkward counter pressure.",
    defense: 9,
    offense: 7,
  },
  {
    id: "harsetti",
    name: "Harsetti",
    short: "Harsetti",
    element: "dark",
    class: "mage",
    tier: "SS",
    roles: ["speedcap", "control"],
    tags: ["cr-cut", "aoe"],
    kit: "Hard-caps enemy speed to hers. A 300-speed cleave into Harsetti is a dead draft.",
    defense: 10,
    offense: 6,
  },
  {
    id: "briar-witch-iseria",
    name: "Briar Witch Iseria",
    short: "B.Iseria",
    element: "dark",
    class: "ranger",
    tier: "SS",
    roles: ["strip", "dps"],
    tags: ["strip", "anti-revive", "ignore-er", "defbreak"],
    kit: "Strip that ignores Effect Resistance. Required tech into Ruele / Maid Chloe walls.",
    defense: 4,
    offense: 10,
  },
  {
    id: "ambitious-tywin",
    name: "Ambitious Tywin",
    short: "A.Tywin",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["opener", "strip", "tank"],
    tags: ["stun", "strip", "cr-push", "aoe"],
    kit: "Swiss-army opener: strip, stun, CR. Fits almost every offense draft.",
    defense: 6,
    offense: 9,
  },
  {
    id: "belian",
    name: "Belian",
    short: "Belian",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["soulblock", "bruiser"],
    tags: ["unhealable", "aoe", "counter"],
    kit: "Soul lock. Cuts soulburn cleaves and leaks chip damage on counter.",
    defense: 9,
    offense: 7,
  },
  {
    id: "blood-moon-haste",
    name: "Blood Moon Haste",
    short: "BM Haste",
    element: "dark",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "dps"],
    tags: ["anti-revive", "unhealable"],
    kit: "Anti-revive plus sustain. The backup plan when B.Iseria is not built.",
    defense: 6,
    offense: 8,
  },
  {
    id: "conqueror-lilias",
    name: "Conqueror Lilias",
    short: "C.Lilias",
    element: "light",
    class: "warrior",
    tier: "S",
    roles: ["opener", "control"],
    tags: ["dual-attack", "cr-push", "provoke"],
    kit: "Forces dual attacks. Pairs with counter-set bruisers and turn-2 teams.",
    defense: 7,
    offense: 8,
  },
  {
    id: "death-dealer-ray",
    name: "Death Dealer Ray",
    short: "DD Ray",
    element: "dark",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "cleanse", "dps"],
    tags: ["aoe", "barrier"],
    kit: "Heals, cleanses, and still deals damage in long fights.",
    defense: 7,
    offense: 7,
  },
  {
    id: "dragon-bride-senya",
    name: "Dragon Bride Senya",
    short: "DB Senya",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["tank", "bruiser"],
    tags: ["barrier", "counter", "immunity"],
    kit: "Fat knight with team utility. Anchors Harsetti and injury stalls.",
    defense: 9,
    offense: 6,
  },
  {
    id: "fallen-cecilia",
    name: "Fallen Cecilia",
    short: "F.Cecilia",
    element: "dark",
    class: "knight",
    tier: "S",
    roles: ["tank", "revive"],
    tags: ["barrier", "provoke"],
    kit: "Barrier tank with a revive. Classic slow-wall piece against aggressive openers.",
    defense: 9,
    offense: 4,
  },
  {
    id: "frieren",
    name: "Frieren",
    short: "Frieren",
    element: "earth",
    class: "mage",
    tier: "S",
    roles: ["control", "dps"],
    tags: ["cr-cut", "silence", "aoe"],
    kit: "Turn-2 control mage. Limits enemy CR and holds the mid-fight.",
    defense: 7,
    offense: 8,
  },
  {
    id: "genesis-ras",
    name: "Genesis Ras",
    short: "G.Ras",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["opener", "tank"],
    tags: ["immunity", "cr-push", "seal"],
    kit: "Team-wide immunity opener. The cleanest way to enter a control fight.",
    defense: 7,
    offense: 9,
  },
  {
    id: "lone-wolf-peira",
    name: "Lone Wolf Peira",
    short: "LW Peira",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["opener", "strip"],
    tags: ["strip", "cr-push", "stun"],
    kit: "Opener with Swift Attack generation. Wants 280+ speed to own the first cycle.",
    defense: 5,
    offense: 9,
  },
  {
    id: "sea-phantom-politis",
    name: "Sea Phantom Politis",
    short: "SP Politis",
    element: "dark",
    class: "ranger",
    tier: "S",
    roles: ["control", "soulblock"],
    tags: ["cr-cut", "silence"],
    kit: "Disrupts soul and CR. Painful on both offense and sticky defenses.",
    defense: 8,
    offense: 8,
  },
  {
    id: "setsuka",
    name: "Setsuka",
    short: "Setsuka",
    element: "fire",
    class: "thief",
    tier: "S",
    roles: ["evasion", "dps"],
    tags: ["evade", "counter", "extra-turn"],
    kit: "Evasion plus counter damage. CR-heavy teams whiff and die to the bounce.",
    defense: 8,
    offense: 8,
  },
  {
    id: "witch-of-the-mere-tenebria",
    name: "Witch of the Mere Tenebria",
    short: "WMeri",
    element: "light",
    class: "mage",
    tier: "S",
    roles: ["control", "dps"],
    tags: ["stun", "cr-cut", "aoe"],
    kit: "Control mage with stun chains. Holds mid-rank and still drafts in RTA.",
    defense: 6,
    offense: 8,
  },
  {
    id: "shepherd-diene",
    name: "Shepherd of the Dark Diene",
    short: "ML Diene",
    element: "dark",
    class: "mage",
    tier: "S",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "barrier"],
    kit: "Immunity chain support. Keeps turn-2 teams alive through the first AoE.",
    defense: 8,
    offense: 6,
  },
  {
    id: "urban-shadow-choux",
    name: "Urban Shadow Choux",
    short: "US Choux",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["injury", "counter"],
    kit: "Injury bruiser on a counter kit. Excellent into dual-attack and long fights.",
    defense: 8,
    offense: 8,
  },
  {
    id: "last-rider-krau",
    name: "Last Rider Krau",
    short: "LR Krau",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["tank", "dps"],
    tags: ["immunity", "aoe", "invincible"],
    kit: "AoE immunity tank that still hits. Pairs with Harsetti to ruin cleaves.",
    defense: 9,
    offense: 7,
  },
  {
    id: "navy-captain-landy",
    name: "Navy Captain Landy",
    short: "NC Landy",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["counter", "aoe", "dual-attack"],
    kit: "Counter-set DPS. Punishes dual-attack teams and wins extended trades.",
    defense: 7,
    offense: 8,
  },
  {
    id: "hecate",
    name: "Hecate",
    short: "Hecate",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["injury", "aoe"],
    kit: "Modern bruiser with injury pressure. A clean Harsetti-answer piece.",
    defense: 7,
    offense: 8,
  },
  {
    id: "notos",
    name: "Notos",
    short: "Notos",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["tank", "control"],
    tags: ["stun", "barrier", "immunity"],
    kit: "Frontline control knight. Hard to draft around if left open.",
    defense: 8,
    offense: 7,
  },
  {
    id: "eternal-wanderer-ludwig",
    name: "Eternal Wanderer Ludwig",
    short: "EW Ludwig",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["cleave", "dps"],
    tags: ["aoe", "soulburn", "defbreak"],
    kit: "Soulburn cleave mage. Strong until Emperor, where evasion walls eat him.",
    defense: 3,
    offense: 8,
  },
  {
    id: "remnant-violet",
    name: "Remnant Violet",
    short: "R.Violet",
    element: "dark",
    class: "thief",
    tier: "A",
    roles: ["evasion", "dps"],
    tags: ["evade", "counter"],
    kit: "Evasion anchor. Single-target hitters miss, then eat the counter.",
    defense: 8,
    offense: 7,
  },
  {
    id: "ran",
    name: "Ran",
    short: "Ran",
    element: "ice",
    class: "thief",
    tier: "A",
    roles: ["opener", "strip"],
    tags: ["strip", "cr-push", "defbreak"],
    kit: "Classic ice opener. Still climbs mid-high if the speed floor is real.",
    defense: 3,
    offense: 8,
  },
  {
    id: "apocalypse-ravi",
    name: "Apocalypse Ravi",
    short: "A.Ravi",
    element: "dark",
    class: "warrior",
    tier: "A",
    roles: ["bruiser", "tank"],
    tags: ["injury", "counter"],
    kit: "Self-sufficient injury bruiser. Alternative to E.Ilynav on a budget.",
    defense: 8,
    offense: 7,
  },
  {
    id: "mediator-kawerik",
    name: "Mediator Kawerik",
    short: "ML Kawerik",
    element: "dark",
    class: "warrior",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["cr-cut", "seal"],
    kit: "Blocks combat-readiness transfers. Wrecks CR-push compositions.",
    defense: 6,
    offense: 8,
  },
  {
    id: "maid-chloe",
    name: "Maid Chloe",
    short: "Maid Chloe",
    element: "light",
    class: "soulweaver",
    tier: "A",
    roles: ["revive", "healer"],
    tags: ["invincible", "barrier"],
    kit: "Revive option if Ruele is missing. Still holds Champion defenses.",
    defense: 8,
    offense: 4,
  },
  {
    id: "spirit-eye-celine",
    name: "Spirit Eye Celine",
    short: "SE Celine",
    element: "light",
    class: "thief",
    tier: "A",
    roles: ["dps", "strip"],
    tags: ["strip", "extra-turn", "evade"],
    kit: "Buff steal on a fast cycle. Punishes stacked immunity and barriers.",
    defense: 6,
    offense: 8,
  },
  {
    id: "abyssal-yufine",
    name: "Abyssal Yufine",
    short: "A.Yufine",
    element: "dark",
    class: "knight",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["stun", "aoe", "defbreak"],
    kit: "Stun into damage. A reliable flex DPS into clumped defenses.",
    defense: 5,
    offense: 8,
  },
  {
    id: "amid",
    name: "Amid",
    short: "Amid",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["cr-push", "immunity"],
    kit: "CR-push healer. Enables extra turns for your win condition.",
    defense: 6,
    offense: 7,
  },
  {
    id: "choux",
    name: "Choux",
    short: "Choux",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["bruiser", "tank"],
    tags: ["barrier", "counter"],
    kit: "Barrier bruiser. Simple, tanky, and still drafts on defense.",
    defense: 7,
    offense: 6,
  },
  {
    id: "closer-charles",
    name: "Closer Charles",
    short: "C.Charles",
    element: "dark",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "defbreak"],
    kit: "Extra-attack thief. Punishes buffed walls if the strip lands.",
    defense: 4,
    offense: 8,
  },
  {
    id: "crimson-armin",
    name: "Crimson Armin",
    short: "C.Armin",
    element: "light",
    class: "knight",
    tier: "A",
    roles: ["tank"],
    tags: ["provoke", "barrier", "invincible"],
    kit: "Provoke tank. Classic anti-cleave piece for Gold through Master.",
    defense: 8,
    offense: 3,
  },
  {
    id: "diene",
    name: "Diene",
    short: "Diene",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "barrier"],
    kit: "Attack buff plus immunity. Still the cheapest way to protect a wincon.",
    defense: 5,
    offense: 7,
  },
  {
    id: "elena",
    name: "Elena",
    short: "Elena",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["aoe", "cr-cut"],
    kit: "AoE cleanse and CR cut. Softens control teams.",
    defense: 6,
    offense: 5,
  },
  {
    id: "eligos",
    name: "Eligos",
    short: "Eligos",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "defbreak"],
    kit: "Fire ranger DPS. Useful as a dedicated cleave closer.",
    defense: 3,
    offense: 7,
  },
  {
    id: "jenua",
    name: "Jenua",
    short: "Jenua",
    element: "fire",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "defbreak"],
    kit: "Single-target assassin. Deletes a key unit if he takes the turn.",
    defense: 3,
    offense: 8,
  },
  {
    id: "krau",
    name: "Krau",
    short: "Krau",
    element: "ice",
    class: "knight",
    tier: "A",
    roles: ["tank", "dps"],
    tags: ["provoke", "fixed-dmg", "invincible"],
    kit: "HP-scaling nuke on S3. Still a Champion-viable surprise defense.",
    defense: 7,
    offense: 6,
  },
  {
    id: "lilias",
    name: "Lilias",
    short: "Lilias",
    element: "fire",
    class: "knight",
    tier: "A",
    roles: ["opener", "tank"],
    tags: ["cr-push", "provoke", "aoe"],
    kit: "CR-push opener with provoke. Budget G.Ras for many accounts.",
    defense: 6,
    offense: 7,
  },
  {
    id: "milim",
    name: "Milim",
    short: "Milim",
    element: "fire",
    class: "mage",
    tier: "A",
    roles: ["cleave", "dps"],
    tags: ["aoe", "soulburn", "extra-turn"],
    kit: "Soulburn cleave. Mid-rank ladder tool, falls off versus evasion.",
    defense: 2,
    offense: 8,
  },
  {
    id: "mort",
    name: "Mort",
    short: "Mort",
    element: "earth",
    class: "knight",
    tier: "A",
    roles: ["tank", "soulblock"],
    tags: ["immunity", "counter", "aoe"],
    kit: "Anti-buff tank. Punishes teams that stack immunity and attack buffs.",
    defense: 8,
    offense: 5,
  },
  {
    id: "nahkwol",
    name: "Nahkwol",
    short: "Nahkwol",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["unhealable", "defbreak"],
    kit: "Unhealable ranger. Pairs with injury to stop walls from recovering.",
    defense: 5,
    offense: 7,
  },
  {
    id: "pirate-captain-flan",
    name: "Pirate Captain Flan",
    short: "PC Flan",
    element: "dark",
    class: "ranger",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "cr-push", "defbreak"],
    kit: "Strip plus CR. A cleaner Ran-line opener for dark-heavy drafts.",
    defense: 4,
    offense: 8,
  },
  {
    id: "politis",
    name: "Politis",
    short: "Politis",
    element: "fire",
    class: "mage",
    tier: "A",
    roles: ["soulblock", "control"],
    tags: ["cr-cut", "aoe"],
    kit: "Covenant soulblock. Stops extra turns and soulburn at a lower cost.",
    defense: 7,
    offense: 6,
  },
  {
    id: "requiem-roana",
    name: "Requiem Roana",
    short: "RQ Roana",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["healer", "control"],
    tags: ["counter", "barrier"],
    kit: "Anti-extra-turn healer. Punishes dual-attack and extra-attack cores.",
    defense: 8,
    offense: 5,
  },
  {
    id: "roy-mustang",
    name: "Roy Mustang",
    short: "Mustang",
    element: "fire",
    class: "mage",
    tier: "A",
    roles: ["cleave", "dps"],
    tags: ["aoe", "defbreak", "soulburn"],
    kit: "AoE fire mage. Mid-ladder cleave closer with a high damage ceiling.",
    defense: 2,
    offense: 8,
  },
  {
    id: "sage-baal",
    name: "Sage Baal & Sezan",
    short: "Sage Baal",
    element: "light",
    class: "mage",
    tier: "A",
    roles: ["control", "cleave"],
    tags: ["stun", "aoe", "cr-cut"],
    kit: "AoE stun mage. G.Ras exists specifically to make this unit sad.",
    defense: 5,
    offense: 8,
  },
  {
    id: "schniel",
    name: "Schniel",
    short: "Schniel",
    element: "earth",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "cr-push"],
    kit: "Cleanse plus immunity soul weaver. Stabilizes bruiser drafts.",
    defense: 6,
    offense: 6,
  },
  {
    id: "shalltear",
    name: "Shalltear",
    short: "Shalltear",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["aoe", "defbreak"],
    kit: "Fire warrior DPS with a greedy damage profile. Needs setup.",
    defense: 4,
    offense: 7,
  },
  {
    id: "sharun",
    name: "Sharun",
    short: "Sharun",
    element: "earth",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "control"],
    tags: ["barrier", "cr-push"],
    kit: "Support that enables turn-2. Often paired with Fenne-style control.",
    defense: 6,
    offense: 6,
  },
  {
    id: "solitaria",
    name: "Solitaria of the Snow",
    short: "Solitaria",
    element: "light",
    class: "mage",
    tier: "A",
    roles: ["control"],
    tags: ["stun", "seal", "cr-cut"],
    kit: "Seal plus stun. Stops revive and CR shenanigans from ever starting.",
    defense: 8,
    offense: 6,
  },
  {
    id: "straze",
    name: "Straze",
    short: "Straze",
    element: "dark",
    class: "warrior",
    tier: "A",
    roles: ["cleave", "dps"],
    tags: ["aoe", "defbreak", "ignore-er"],
    kit: "Ignore-defense AoE. The classic cleave closer if the strip landed.",
    defense: 3,
    offense: 9,
  },
  {
    id: "zahhak",
    name: "Zahhak",
    short: "Zahhak",
    element: "earth",
    class: "warrior",
    tier: "A",
    roles: ["cleave", "dps"],
    tags: ["aoe", "extra-turn", "defbreak"],
    kit: "Earth cleave warrior. A reliable Rank-up tool through Champion.",
    defense: 3,
    offense: 8,
  },
  {
    id: "zio",
    name: "Zio",
    short: "Zio",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["opener", "control"],
    tags: ["stun", "extra-turn", "invincible"],
    kit: "Invincible extra-turn opener. Can steal games before the wall acts.",
    defense: 5,
    offense: 8,
  },
  {
    id: "ae-karina",
    name: "ae-KARINA",
    short: "Karina",
    element: "ice",
    class: "knight",
    tier: "A",
    roles: ["tank", "bruiser"],
    tags: ["counter", "barrier"],
    kit: "Counter knight. Holds the line in mixed bruiser defenses.",
    defense: 7,
    offense: 6,
  },
  {
    id: "peira",
    name: "Peira",
    short: "Peira",
    element: "ice",
    class: "thief",
    tier: "A",
    roles: ["opener", "strip"],
    tags: ["strip", "stun", "cr-push"],
    kit: "Covenant opener. The most common first-pick speed unit on a new account.",
    defense: 3,
    offense: 8,
  },
  {
    id: "flan",
    name: "Flan",
    short: "Flan",
    element: "ice",
    class: "ranger",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "cr-push", "defbreak"],
    kit: "Defense break plus strip. Core enabler for mid-rank cleave.",
    defense: 3,
    offense: 8,
  },
  {
    id: "landy",
    name: "Landy",
    short: "Landy",
    element: "earth",
    class: "ranger",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "counter"],
    kit: "Attack-scaling ranger. Punishes buffed teams and still cleaves.",
    defense: 4,
    offense: 7,
  },
  {
    id: "hwayoung",
    name: "Hwayoung",
    short: "Hwayoung",
    element: "fire",
    class: "warrior",
    tier: "B",
    roles: ["dps"],
    tags: ["fixed-dmg", "injury"],
    kit: "Single-target nuke. Still deletes a squishy if she takes the turn.",
    defense: 3,
    offense: 7,
  },
  {
    id: "bystander-hwayoung",
    name: "Bystander Hwayoung",
    short: "ML Hwayoung",
    element: "dark",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["fixed-dmg", "injury"],
    kit: "Dark Hwayoung. A scare pick on defense when the HP threshold is real.",
    defense: 6,
    offense: 8,
  },
  {
    id: "roana",
    name: "Roana",
    short: "Roana",
    element: "earth",
    class: "soulweaver",
    tier: "A",
    roles: ["healer"],
    tags: ["counter", "barrier"],
    kit: "Anti-counter-attack healer. Punishes extra-attack cores on defense.",
    defense: 8,
    offense: 4,
  },
  {
    id: "senya",
    name: "Senya",
    short: "Senya",
    element: "earth",
    class: "knight",
    tier: "A",
    roles: ["tank", "dps"],
    tags: ["barrier", "fixed-dmg"],
    kit: "Effect-resistance tank with a surprising S3. Gold-to-Master staple.",
    defense: 8,
    offense: 5,
  },
  {
    id: "alencia",
    name: "Alencia",
    short: "Alencia",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["bruiser", "strip"],
    tags: ["strip", "aoe", "defbreak"],
    kit: "Strip bruiser. A cheap way to answer buffed walls.",
    defense: 6,
    offense: 6,
  },
  {
    id: "destina",
    name: "Destina",
    short: "Destina",
    element: "earth",
    class: "soulweaver",
    tier: "B",
    roles: ["healer", "cleanse", "revive"],
    tags: ["aoe"],
    kit: "Full cleanse plus revive. Still a fine Master support.",
    defense: 6,
    offense: 4,
  },
  {
    id: "seaside-bellona",
    name: "Seaside Bellona",
    short: "SSB",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["dps", "bruiser"],
    tags: ["counter", "defbreak", "aoe"],
    kit: "Counter ranger. Punishes AoE and still defense-breaks.",
    defense: 7,
    offense: 6,
  },
  {
    id: "arbiter-vildred",
    name: "Arbiter Vildred",
    short: "A.Vildred",
    element: "dark",
    class: "thief",
    tier: "B",
    roles: ["cleave", "dps"],
    tags: ["aoe", "soulburn", "extra-turn"],
    kit: "The original soulburn cleave. Still farm Gold if the strip is there.",
    defense: 2,
    offense: 7,
  },
  {
    id: "specter-tenebria",
    name: "Specter Tenebria",
    short: "Spec Tene",
    element: "dark",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["unhealable", "extra-turn"],
    kit: "Unhealable plus extra turn. Deletes a key soul weaver.",
    defense: 4,
    offense: 7,
  },
  {
    id: "lionheart-cermia",
    name: "Lionheart Cermia",
    short: "LH Cermia",
    element: "light",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["fixed-dmg", "ignore-er"],
    kit: "Ignore-defense firebrand. A clean answer to fat HP knights.",
    defense: 4,
    offense: 8,
  },
  {
    id: "little-queen-charlotte",
    name: "Little Queen Charlotte",
    short: "LQ Charlotte",
    element: "light",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Light warrior cleave. Punishes Earth cores and still one-shots squishies.",
    defense: 4,
    offense: 8,
  },
  {
    id: "angel-of-light-angelica",
    name: "Angel of Light Angelica",
    short: "AOL Angelica",
    element: "light",
    class: "mage",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "invincible"],
    kit: "Invincibility plus cleanse. A panic button for bruiser drafts.",
    defense: 7,
    offense: 5,
  },
  {
    id: "dragon-king-sharun",
    name: "Dragon King Sharun",
    short: "DK Sharun",
    element: "light",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "control"],
    tags: ["barrier", "cr-push"],
    kit: "Light support that holds control drafts together.",
    defense: 7,
    offense: 6,
  },
  {
    id: "iseria",
    name: "Iseria",
    short: "Iseria",
    element: "earth",
    class: "ranger",
    tier: "B",
    roles: ["strip", "opener"],
    tags: ["strip", "defbreak", "unhealable"],
    kit: "The original strip. Still enables every budget cleave.",
    defense: 2,
    offense: 7,
  },
  {
    id: "tywin",
    name: "Tywin",
    short: "Tywin",
    element: "ice",
    class: "knight",
    tier: "B",
    roles: ["opener", "tank"],
    tags: ["defbreak", "cr-push", "aoe"],
    kit: "AoE defense break opener. A stepping stone to A.Tywin.",
    defense: 5,
    offense: 6,
  },
  {
    id: "operator-sigret",
    name: "Operator Sigret",
    short: "O.Sigret",
    element: "dark",
    class: "ranger",
    tier: "B",
    roles: ["dps"],
    tags: ["defbreak", "unhealable"],
    kit: "Single-target execute. Deletes the remaining knight after injury stacks.",
    defense: 3,
    offense: 7,
  },
  {
    id: "dark-corvus",
    name: "Dark Corvus",
    short: "D.Corvus",
    element: "dark",
    class: "warrior",
    tier: "B",
    roles: ["bruiser", "tank"],
    tags: ["fixed-dmg", "injury"],
    kit: "One-shot counter to glass mages. Slow, obvious, still works on defense.",
    defense: 7,
    offense: 5,
  },
  {
    id: "adventurer-ras",
    name: "Adventurer Ras",
    short: "A.Ras",
    element: "fire",
    class: "knight",
    tier: "B",
    roles: ["opener", "tank"],
    tags: ["defbreak", "immunity", "cr-push"],
    kit: "Free unit opener. Every account should have him built for Gold.",
    defense: 5,
    offense: 6,
  },
  {
    id: "astromancer-elena",
    name: "Astromancer Elena",
    short: "A.Elena",
    element: "light",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "control"],
    tags: ["cr-push", "dual-attack", "extra-turn"],
    kit: "CR and extra-attack support. Feeds dual-attack and turn-2 teams.",
    defense: 6,
    offense: 6,
  },
  {
    id: "commander-pavel",
    name: "Commander Pavel",
    short: "C.Pavel",
    element: "light",
    class: "ranger",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "ignore-er", "cr-cut"],
    kit: "AoE ranger that ignores Effect Resistance. A clean pick into bulky mages.",
    defense: 4,
    offense: 8,
  },
  {
    id: "faithless-lidica",
    name: "Faithless Lidica",
    short: "F.Lidica",
    element: "light",
    class: "ranger",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Extra attacks and CR. Takes over the first cycle if she is left open.",
    defense: 5,
    offense: 8,
  },
  {
    id: "architect-laika",
    name: "Architect Laika",
    short: "A.Laika",
    element: "light",
    class: "mage",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["extra-turn", "aoe", "dual-attack"],
    kit: "Extra-attack mage. Converts one opening into a full cycle of hits.",
    defense: 5,
    offense: 9,
  },
  {
    id: "silver-blade-aramintha",
    name: "Silver Blade Aramintha",
    short: "SB Ara",
    element: "light",
    class: "mage",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["stun", "counter", "aoe"],
    kit: "Stun mage with a counter kit. Holds mid-fight if the first AoE lands.",
    defense: 6,
    offense: 7,
  },
  {
    id: "sylvan-sage-vivian",
    name: "Sylvan Sage Vivian",
    short: "SS Vivian",
    element: "light",
    class: "mage",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["extra-turn", "aoe", "soulburn"],
    kit: "Extra-turn AoE mage. Soulburn ends the cycle if the wall is already cracked.",
    defense: 4,
    offense: 8,
  },
  {
    id: "desert-jewel-basar",
    name: "Desert Jewel Basar",
    short: "DJ Basar",
    element: "light",
    class: "soulweaver",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "cr-push", "aoe"],
    kit: "AoE strip plus CR. The classic way to open a buffed wall.",
    defense: 5,
    offense: 8,
  },
  {
    id: "lisette",
    name: "Lisette",
    short: "Lisette",
    element: "light",
    class: "soulweaver",
    tier: "S",
    roles: ["revive", "healer"],
    tags: ["invincible", "cr-push", "immunity"],
    kit: "Revive soul weaver. Turns a pick into a fragment, then rolls the fight back.",
    defense: 9,
    offense: 5,
  },
  {
    id: "judge-kise",
    name: "Judge Kise",
    short: "J.Kise",
    element: "light",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack warrior. Ignores fat Defense and deletes the backline.",
    defense: 4,
    offense: 8,
  },
  {
    id: "successor-taeyou",
    name: "Successor Taeyou",
    short: "S.Taeyou",
    element: "light",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "dual-attack", "aoe"],
    kit: "Extra-turn bruiser. Turns one dual-attack into a long, messy fight.",
    defense: 7,
    offense: 8,
  },
  {
    id: "monarch-of-the-sword-iseria",
    name: "Monarch of the Sword Iseria",
    short: "MS Iseria",
    element: "light",
    class: "knight",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["injury", "counter", "cr-push"],
    kit: "Injury knight on a counter kit. Punishes hits and stacks the long fight.",
    defense: 8,
    offense: 8,
  },
  {
    id: "specimen-sez",
    name: "Specimen Sez",
    short: "S.Sez",
    element: "light",
    class: "thief",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Extra-attack thief. Finishes low-HP units after the first cut.",
    defense: 4,
    offense: 8,
  },
  {
    id: "twisted-eidolon-kayron",
    name: "Twisted Eidolon Kayron",
    short: "TE Kayron",
    element: "light",
    class: "thief",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["counter", "extra-turn", "unhealable"],
    kit: "Counter thief. Lives the first hit, then takes extra turns and shuts down heals.",
    defense: 7,
    offense: 9,
  },
  {
    id: "designer-lilibet",
    name: "Designer Lilibet",
    short: "D.Lilibet",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["unhealable", "ignore-er", "extra-turn"],
    kit: "Extra-attack warrior. Lands unhealable through Effect Resistance — a clean evasion answer.",
    defense: 6,
    offense: 9,
  },
  {
    id: "disciplinary-prefect-aria",
    name: "Disciplinary Prefect Aria",
    short: "DP Aria",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "tank"],
    tags: ["injury", "extra-turn", "cr-push"],
    kit: "HP-scaling injury bruiser. Extra attacks stack the long fight.",
    defense: 8,
    offense: 8,
  },
  {
    id: "lone-crescent-bellona",
    name: "Lone Crescent Bellona",
    short: "LC Bellona",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["aoe", "immunity", "cr-push"],
    kit: "Crit warrior. Builds fighting spirit, then AoE and CR on the extra cycle.",
    defense: 6,
    offense: 9,
  },
  {
    id: "martial-artist-ken",
    name: "Martial Artist Ken",
    short: "MA Ken",
    element: "dark",
    class: "warrior",
    tier: "A",
    roles: ["bruiser", "dps"],
    tags: ["counter", "stun"],
    kit: "Counter bruiser. Stuns on the bounce and wins ugly 1v1s.",
    defense: 8,
    offense: 7,
  },
  {
    id: "salome",
    name: "Salome",
    short: "Salome",
    element: "dark",
    class: "warrior",
    tier: "S",
    roles: ["control", "bruiser"],
    tags: ["dual-attack", "seal", "extra-turn"],
    kit: "Control warrior. Clones a skill and turns the fight into her script.",
    defense: 7,
    offense: 8,
  },
  {
    id: "rhianna-and-luciella",
    name: "Rhianna and Luciella",
    short: "R&L",
    element: "dark",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Extra-attack thief. Two bodies, one cycle — CR and hits stack fast.",
    defense: 5,
    offense: 8,
  },
  {
    id: "hellion-lua",
    name: "Hellion Lua",
    short: "H.Lua",
    element: "dark",
    class: "ranger",
    tier: "S",
    roles: ["control", "tank"],
    tags: ["provoke", "cr-push", "counter", "ignore-er"],
    kit: "AoE provoke that ignores Effect Resistance. Allies counter after she is hit.",
    defense: 8,
    offense: 6,
  },
  {
    id: "ainz-ooal-gown",
    name: "Ainz Ooal Gown",
    short: "Ainz",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["unhealable", "aoe", "extra-turn"],
    kit: "AoE mage. Unhealable plus extra attacks if the first cycle lands.",
    defense: 5,
    offense: 8,
  },
  {
    id: "archdemons-shadow",
    name: "Archdemon's Shadow",
    short: "ADS",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Extra-turn control mage. Steals the cycle after the first skill.",
    defense: 5,
    offense: 8,
  },
  {
    id: "tidal-rift-elvira",
    name: "Tidal Rift Elvira",
    short: "TR Elvira",
    element: "dark",
    class: "mage",
    tier: "S",
    roles: ["control", "dps"],
    tags: ["seal", "cr-push", "aoe"],
    kit: "Seal and curse mage. Extra attacks absorb HP and scramble CR.",
    defense: 6,
    offense: 9,
  },
  {
    id: "top-model-luluca",
    name: "Top Model Luluca",
    short: "TM Lulu",
    element: "dark",
    class: "mage",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["extra-turn", "cr-cut", "aoe"],
    kit: "Extra-turn mage. Cuts CR and takes a second skill in the same cycle.",
    defense: 5,
    offense: 8,
  },
  {
    id: "arunka",
    name: "Arunka",
    short: "Arunka",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["injury", "extra-turn", "aoe"],
    kit: "Injury warrior. Extra attacks stack the long fight and ignore fat HP.",
    defense: 7,
    offense: 8,
  },
  {
    id: "immortal-wukong",
    name: "Immortal Wukong",
    short: "Wukong",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "tank"],
    tags: ["barrier", "extra-turn", "invincible"],
    kit: "Bruiser who refuses to stay down. Lives the first cycle, then takes extra turns.",
    defense: 8,
    offense: 8,
  },
  {
    id: "laia",
    name: "Laia",
    short: "Laia",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["control", "bruiser"],
    tags: ["dual-attack", "cr-push", "extra-turn"],
    kit: "Dual-attack engine. Feeds the team extra hits and CR.",
    defense: 6,
    offense: 7,
  },
  {
    id: "lilibet",
    name: "Lilibet",
    short: "Lilibet",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["dps"],
    tags: ["unhealable", "extra-turn"],
    kit: "Unhealable extra attacks. Niche, still useful into sustain walls.",
    defense: 4,
    offense: 7,
  },
  {
    id: "mui",
    name: "Mui",
    short: "Mui",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["control", "opener"],
    tags: ["stun", "cr-push", "aoe"],
    kit: "AoE stun opener. Old, but still drafts when the wall is slow.",
    defense: 4,
    offense: 7,
  },
  {
    id: "rimuru",
    name: "Rimuru",
    short: "Rimuru",
    element: "earth",
    class: "warrior",
    tier: "S",
    roles: ["control", "dps"],
    tags: ["extra-turn", "aoe", "strip"],
    kit: "Extra-turn collab warrior. Copies a skill and takes over the cycle.",
    defense: 6,
    offense: 8,
  },
  {
    id: "yufine",
    name: "Yufine",
    short: "Yufine",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["stun", "aoe"],
    kit: "AoE stun warrior. Simple closer if the wall is already cracked.",
    defense: 4,
    offense: 7,
  },
  {
    id: "albedo",
    name: "Albedo",
    short: "Albedo",
    element: "earth",
    class: "knight",
    tier: "A",
    roles: ["tank", "bruiser"],
    tags: ["barrier", "provoke"],
    kit: "Barrier knight. Holds the front while the rest of the draft works.",
    defense: 8,
    offense: 5,
  },
  {
    id: "charles",
    name: "Charles",
    short: "Charles",
    element: "earth",
    class: "knight",
    tier: "A",
    roles: ["dps", "tank"],
    tags: ["dual-attack", "extra-turn", "aoe"],
    kit: "Dual-attack knight. Extra hits on counter and on the S3.",
    defense: 7,
    offense: 7,
  },
  {
    id: "estelle",
    name: "Estelle",
    short: "Estelle",
    element: "earth",
    class: "knight",
    tier: "A",
    roles: ["tank", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "CR knight. Extra turns and a frontline that still pushes the team.",
    defense: 7,
    offense: 6,
  },
  {
    id: "yulha",
    name: "Yulha",
    short: "Yulha",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["dps", "bruiser"],
    tags: ["stun", "extra-turn"],
    kit: "Stun warrior. Older kit, still fills a bruiser slot.",
    defense: 5,
    offense: 7,
  },
  {
    id: "baiken",
    name: "Baiken",
    short: "Baiken",
    element: "earth",
    class: "warrior",
    tier: "B",
    roles: ["dps"],
    tags: ["extra-turn", "counter", "unhealable"],
    kit: "Extra-attack warrior. Punishes a miss and shuts down heals.",
    defense: 5,
    offense: 8,
  },
  {
    id: "blooming-lidica",
    name: "Blooming Lidica",
    short: "B.Lidica",
    element: "earth",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "cr-push"],
    kit: "Speed thief. Gains turns as the fight goes and never lets the wall cycle.",
    defense: 4,
    offense: 8,
  },
  {
    id: "ram",
    name: "Ram",
    short: "Ram",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["aoe", "extra-turn"],
    kit: "Collab AoE mage. Extra attacks if the first skill lands.",
    defense: 4,
    offense: 7,
  },
  {
    id: "vivian",
    name: "Vivian",
    short: "Vivian",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["immunity", "aoe", "extra-turn"],
    kit: "Immunity AoE mage. Old cleave piece that still works in Gold.",
    defense: 4,
    offense: 7,
  },
  {
    id: "ocean-breeze-luluca",
    name: "Ocean Breeze Luluca",
    short: "OB Lulu",
    element: "earth",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["barrier", "cr-push"],
    kit: "Barrier soul weaver. Keeps the bruiser alive through the first AoE.",
    defense: 7,
    offense: 5,
  },
  {
    id: "ray",
    name: "Ray",
    short: "Ray",
    element: "earth",
    class: "soulweaver",
    tier: "B",
    roles: ["healer", "cleanse"],
    tags: ["unhealable", "aoe"],
    kit: "Cleanse plus unhealable. Utility soul weaver for long fights.",
    defense: 6,
    offense: 5,
  },
  {
    id: "young-senya",
    name: "Young Senya",
    short: "Y.Senya",
    element: "earth",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "CR soul weaver. Extra turns and a push that starts the team's cycle.",
    defense: 7,
    offense: 6,
  },
  {
    id: "celine",
    name: "Celine",
    short: "Celine",
    element: "earth",
    class: "thief",
    tier: "B",
    roles: ["dps", "evasion"],
    tags: ["evade", "extra-turn", "counter"],
    kit: "Evasion extra-attack thief. Punishes a single-target S3.",
    defense: 6,
    offense: 7,
  },
  {
    id: "ervalen",
    name: "Ervalen",
    short: "Ervalen",
    element: "earth",
    class: "thief",
    tier: "B",
    roles: ["dps"],
    tags: ["defbreak", "extra-turn"],
    kit: "Def-break extra attacks. A simple closer if someone else opens.",
    defense: 4,
    offense: 7,
  },
  {
    id: "midnight-gala-lilias",
    name: "Midnight Gala Lilias",
    short: "MG Lilias",
    element: "earth",
    class: "thief",
    tier: "S",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "ignore-er"],
    kit: "Limited assassin. Extra attacks that ignore Effect Resistance.",
    defense: 4,
    offense: 9,
  },
  {
    id: "vildred",
    name: "Vildred",
    short: "Vildred",
    element: "earth",
    class: "thief",
    tier: "B",
    roles: ["cleave", "dps"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE extra-attack thief. Classic Gold cleave.",
    defense: 3,
    offense: 7,
  },
  {
    id: "violet",
    name: "Violet",
    short: "Violet",
    element: "earth",
    class: "thief",
    tier: "A",
    roles: ["evasion", "dps"],
    tags: ["evade", "extra-turn", "counter"],
    kit: "Evasion thief. Misses eat the draft, extra attacks finish the rest.",
    defense: 7,
    offense: 7,
  },
  {
    id: "bellona",
    name: "Bellona",
    short: "Bellona",
    element: "earth",
    class: "ranger",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "defbreak"],
    kit: "AoE def-break ranger. Old, still a clean PvE and low-ladder closer.",
    defense: 4,
    offense: 7,
  },
  {
    id: "command-model-laika",
    name: "Command Model Laika",
    short: "CM Laika",
    element: "earth",
    class: "ranger",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["cr-push", "seal"],
    kit: "Target lock ranger. Forces the wall to look at her, then extra attacks.",
    defense: 5,
    offense: 8,
  },
  {
    id: "fenris",
    name: "Fenris",
    short: "Fenris",
    element: "earth",
    class: "ranger",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe", "injury"],
    kit: "Extra-attack ranger. Bruiser-shaped damage that still hits AoE.",
    defense: 6,
    offense: 9,
  },
  {
    id: "pavel",
    name: "Pavel",
    short: "Pavel",
    element: "earth",
    class: "ranger",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "ignore-er", "extra-turn"],
    kit: "Ignore-ER AoE ranger. Soulburn ends a cracked wall.",
    defense: 3,
    offense: 8,
  },
  {
    id: "saria",
    name: "Saria",
    short: "Saria",
    element: "earth",
    class: "ranger",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["cr-push", "aoe", "extra-turn"],
    kit: "CR ranger. Extra attacks and a push that starts the team's cycle.",
    defense: 5,
    offense: 8,
  },
  {
    id: "ae-giselle",
    name: "ae-GISELLE",
    short: "ae-GISELLE",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["aoe", "extra-turn", "cr-cut"],
    kit: "Collab AoE mage. Extra turn if the first skill lands.",
    defense: 4,
    offense: 7,
  },
  {
    id: "basar",
    name: "Basar",
    short: "Basar",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["strip", "opener"],
    tags: ["strip", "stun", "aoe"],
    kit: "AoE strip plus stun. The classic way to open a buffed wall.",
    defense: 4,
    offense: 8,
  },
  {
    id: "eye-of-the-abyss-fumyr",
    name: "Eye of the Abyss Fumyr",
    short: "EotA Fumyr",
    element: "earth",
    class: "mage",
    tier: "S",
    roles: ["control", "dps"],
    tags: ["extra-turn", "cr-cut", "seal"],
    kit: "Control mage. Extra turns and a lock that steals the mid-fight.",
    defense: 6,
    offense: 8,
  },
  {
    id: "ludwig",
    name: "Ludwig",
    short: "Ludwig",
    element: "earth",
    class: "mage",
    tier: "B",
    roles: ["cleave", "dps"],
    tags: ["aoe", "soulburn", "invincible"],
    kit: "Soulburn AoE mage. Invincible window, then the wall has to be dead.",
    defense: 3,
    offense: 8,
  },
  {
    id: "chloe",
    name: "Chloe",
    short: "Chloe",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Extra-attack warrior. AoE closer if the wall is already cracked.",
    defense: 4,
    offense: 8,
  },
  {
    id: "lethe",
    name: "Lethe",
    short: "Lethe",
    element: "ice",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "unhealable", "cr-push"],
    kit: "Limited bruiser. Extra attacks, then extinction if the omen stacks.",
    defense: 7,
    offense: 8,
  },
  {
    id: "luna",
    name: "Luna",
    short: "Luna",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["defbreak", "extra-turn"],
    kit: "Def-break extra attacks. A clean closer after the opener.",
    defense: 5,
    offense: 8,
  },
  {
    id: "rem",
    name: "Rem",
    short: "Rem",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "stun", "extra-turn"],
    kit: "AoE stun warrior. Extra attacks if the first cycle lands.",
    defense: 5,
    offense: 8,
  },
  {
    id: "sigret",
    name: "Sigret",
    short: "Sigret",
    element: "ice",
    class: "warrior",
    tier: "A",
    roles: ["dps"],
    tags: ["unhealable", "extra-turn"],
    kit: "Unhealable extra attacks. Punishes sustain walls in a short fight.",
    defense: 4,
    offense: 8,
  },
  {
    id: "taeyou",
    name: "Taeyou",
    short: "Taeyou",
    element: "ice",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "dual-attack", "aoe"],
    kit: "Extra-turn warrior. Dual attacks turn one opening into a full cycle.",
    defense: 6,
    offense: 9,
  },
  {
    id: "brieg",
    name: "Brieg",
    short: "Brieg",
    element: "ice",
    class: "knight",
    tier: "A",
    roles: ["tank", "bruiser"],
    tags: ["barrier", "cr-push"],
    kit: "Barrier knight. Holds the front and still pushes the team.",
    defense: 8,
    offense: 6,
  },
  {
    id: "summer-break-charlotte",
    name: "Summer Break Charlotte",
    short: "SB Charlotte",
    element: "ice",
    class: "knight",
    tier: "A",
    roles: ["tank", "dps"],
    tags: ["aoe", "extra-turn", "barrier"],
    kit: "Limited knight. Extra attacks off a fat frontline.",
    defense: 7,
    offense: 7,
  },
  {
    id: "argent-waves-hwayoung",
    name: "Argent Waves Hwayoung",
    short: "AW Hwayoung",
    element: "ice",
    class: "thief",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["extra-turn", "aoe", "strip"],
    kit: "Limited thief. Extra attacks after a non-attack skill, then AoE.",
    defense: 4,
    offense: 9,
  },
  {
    id: "elvira",
    name: "Elvira",
    short: "Elvira",
    element: "ice",
    class: "thief",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "cr-push"],
    kit: "Extra-attack thief. Takes the cycle if she is left open.",
    defense: 4,
    offense: 8,
  },
  {
    id: "kise",
    name: "Kise",
    short: "Kise",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE ranger. Old cleave piece that still works in Gold.",
    defense: 3,
    offense: 7,
  },
  {
    id: "sez",
    name: "Sez",
    short: "Sez",
    element: "ice",
    class: "thief",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Extra-attack thief. Finishes low-HP units after the first cut.",
    defense: 3,
    offense: 7,
  },
  {
    id: "birgitta",
    name: "Birgitta",
    short: "Birgitta",
    element: "ice",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "barrier", "immunity"],
    kit: "CR soul weaver. Immunity window plus a push that starts the cycle.",
    defense: 8,
    offense: 6,
  },
  {
    id: "emilia",
    name: "Emilia",
    short: "Emilia",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "cr-push"],
    kit: "Cleanse plus immunity. Keeps the bruiser alive through the first AoE.",
    defense: 7,
    offense: 5,
  },
  {
    id: "fenne",
    name: "Fenne",
    short: "Fenne",
    element: "ice",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "CR soul weaver. Extra turns and a push that owns the mid-fight.",
    defense: 7,
    offense: 6,
  },
  {
    id: "frida",
    name: "Frida",
    short: "Frida",
    element: "ice",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "cr-push"],
    kit: "Team immunity soul weaver. The clean way to enter a control fight.",
    defense: 7,
    offense: 5,
  },
  {
    id: "tactical-archetype-coli",
    name: "Tactical Archetype Coli",
    short: "TA Coli",
    element: "ice",
    class: "thief",
    tier: "S",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "cr-push"],
    kit: "Extra-attack thief. Data-driven cycle steal — speed contest or die.",
    defense: 4,
    offense: 9,
  },
  {
    id: "aubade-ludwig",
    name: "Aubade Ludwig",
    short: "Aubade",
    element: "ice",
    class: "ranger",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn", "soulburn"],
    kit: "Limited ranger. Extra attacks then a soulburn that ends the cycle.",
    defense: 4,
    offense: 9,
  },
  {
    id: "aube",
    name: "Aube",
    short: "Aube",
    element: "ice",
    class: "ranger",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Limited ranger. Extra attacks and a CR push that starts the team's cycle.",
    defense: 5,
    offense: 8,
  },
  {
    id: "byblis",
    name: "Byblis",
    short: "Byblis",
    element: "ice",
    class: "ranger",
    tier: "A",
    roles: ["opener", "control"],
    tags: ["defbreak", "cr-push", "aoe"],
    kit: "Limited speed ranger. Contest turn one, def-break, cut buff duration.",
    defense: 4,
    offense: 8,
  },
  {
    id: "cerise",
    name: "Cerise",
    short: "Cerise",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["opener", "control"],
    tags: ["cr-cut", "unhealable", "aoe"],
    kit: "AoE CR-cut opener. Old, still drafts into greedy speed teams.",
    defense: 4,
    offense: 7,
  },
  {
    id: "lua",
    name: "Lua",
    short: "Lua",
    element: "ice",
    class: "ranger",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "stun", "cr-push"],
    kit: "Strip plus stun. The opener when B.Iseria is not in the draft.",
    defense: 4,
    offense: 8,
  },
  {
    id: "riza-hawkeye",
    name: "Riza Hawkeye",
    short: "Riza",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["dps"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack ranger. Collab closer if the wall is already open.",
    defense: 4,
    offense: 7,
  },
  {
    id: "yuna",
    name: "Yuna",
    short: "Yuna",
    element: "ice",
    class: "ranger",
    tier: "B",
    roles: ["dps", "cleave"],
    tags: ["aoe", "cr-push"],
    kit: "AoE ranger. CR push plus damage — old PvE staple.",
    defense: 4,
    offense: 7,
  },
  {
    id: "aria",
    name: "Aria",
    short: "Aria",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["control", "tank"],
    tags: ["counter", "barrier", "aoe"],
    kit: "Counter mage. Fat, slow, and painful if you hit her.",
    defense: 7,
    offense: 6,
  },
  {
    id: "dizzy",
    name: "Dizzy",
    short: "Dizzy",
    element: "ice",
    class: "mage",
    tier: "A",
    roles: ["control"],
    tags: ["cr-cut", "unhealable", "aoe"],
    kit: "AoE control mage. CR lock plus unhealable — the fight gets slow.",
    defense: 6,
    offense: 6,
  },
  {
    id: "eda",
    name: "Eda",
    short: "Eda",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["aoe", "stun", "extra-turn"],
    kit: "AoE stun mage. Extra attacks if the first skill lands.",
    defense: 4,
    offense: 7,
  },
  {
    id: "fairytale-tenebria",
    name: "Fairytale Tenebria",
    short: "FT Tene",
    element: "ice",
    class: "mage",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["stun", "extra-turn", "aoe"],
    kit: "Stun extra-turn mage. Takes over the cycle after the first skill.",
    defense: 5,
    offense: 8,
  },
  {
    id: "fern",
    name: "Fern",
    short: "Fern",
    element: "ice",
    class: "mage",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn", "ignore-er"],
    kit: "Extra-attack mage. Ignore-ER closer if the wall is already stripped.",
    defense: 4,
    offense: 9,
  },
  {
    id: "fumyr",
    name: "Fumyr",
    short: "Fumyr",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["control", "dps"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-turn mage. Older kit — still fills a control slot.",
    defense: 5,
    offense: 7,
  },
  {
    id: "luluca",
    name: "Luluca",
    short: "Luluca",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["dps", "control"],
    tags: ["defbreak", "aoe"],
    kit: "Def-break mage. Simple enabler for a cleave.",
    defense: 4,
    offense: 7,
  },
  {
    id: "zeno",
    name: "Zeno",
    short: "Zeno",
    element: "ice",
    class: "mage",
    tier: "B",
    roles: ["dps"],
    tags: ["aoe", "extra-turn"],
    kit: "HP-scaling AoE mage. Niche, still a closer if he lives.",
    defense: 5,
    offense: 7,
  },
  {
    id: "abigail",
    name: "Abigail",
    short: "Abigail",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "injury", "aoe"],
    kit: "Injury bruiser. Extra attacks stack the long fight.",
    defense: 7,
    offense: 8,
  },
  {
    id: "aki",
    name: "Aki",
    short: "Aki",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack warrior. Converts one opening into a full cycle of hits.",
    defense: 6,
    offense: 9,
  },
  {
    id: "benimaru",
    name: "Benimaru",
    short: "Benimaru",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE extra-attack warrior. Collab closer if the wall is already cracked.",
    defense: 5,
    offense: 8,
  },
  {
    id: "cermia",
    name: "Cermia",
    short: "Cermia",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["dps"],
    tags: ["extra-turn", "ignore-er"],
    kit: "Single-target extra attacks. Ignores ER and deletes the threat unit.",
    defense: 4,
    offense: 8,
  },
  {
    id: "edward-elric",
    name: "Edward Elric",
    short: "Edward",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack warrior. Collab bruiser that still hits AoE.",
    defense: 6,
    offense: 8,
  },
  {
    id: "guard-captain-krau",
    name: "Guard Captain Krau",
    short: "GC Krau",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["bruiser", "tank"],
    tags: ["barrier", "extra-turn", "aoe"],
    kit: "Limited bruiser. Lives the first cycle, then extra attacks.",
    defense: 8,
    offense: 7,
  },
  {
    id: "holiday-yufine",
    name: "Holiday Yufine",
    short: "H.Yufine",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["aoe", "stun", "extra-turn"],
    kit: "Limited AoE warrior. Stun plus extra attacks — a clean summer closer.",
    defense: 5,
    offense: 9,
  },
  {
    id: "jack-o",
    name: "Jack-O'",
    short: "Jack-O'",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["control", "dps"],
    tags: ["stun", "extra-turn", "dual-attack"],
    kit: "Stun warrior. Extra attacks and a dual-attack engine for the backline.",
    defense: 5,
    offense: 8,
  },
  {
    id: "kane",
    name: "Kane",
    short: "Kane",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe", "unhealable"],
    kit: "Extra-attack warrior. Unhealable closer that still lives a hit.",
    defense: 6,
    offense: 9,
  },
  {
    id: "ken",
    name: "Ken",
    short: "Ken",
    element: "fire",
    class: "warrior",
    tier: "B",
    roles: ["bruiser", "dps"],
    tags: ["counter", "defbreak"],
    kit: "Counter bruiser. Old, still wins ugly 1v1s.",
    defense: 7,
    offense: 6,
  },
  {
    id: "ravi",
    name: "Ravi",
    short: "Ravi",
    element: "fire",
    class: "warrior",
    tier: "A",
    roles: ["bruiser", "dps"],
    tags: ["counter", "extra-turn"],
    kit: "Counter bruiser. Fighting spirit into extra attacks.",
    defense: 7,
    offense: 7,
  },
  {
    id: "sol",
    name: "Sol",
    short: "Sol",
    element: "fire",
    class: "warrior",
    tier: "B",
    roles: ["dps"],
    tags: ["extra-turn", "defbreak"],
    kit: "Extra-attack warrior. Def-break closer if someone else opens.",
    defense: 4,
    offense: 7,
  },
  {
    id: "stark",
    name: "Stark",
    short: "Stark",
    element: "fire",
    class: "warrior",
    tier: "S",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "aoe", "barrier"],
    kit: "Collab extra-attack warrior. Barrier, then a cycle of hits.",
    defense: 6,
    offense: 9,
  },
  {
    id: "cecilia",
    name: "Cecilia",
    short: "Cecilia",
    element: "fire",
    class: "knight",
    tier: "B",
    roles: ["tank", "opener"],
    tags: ["provoke", "defbreak", "aoe"],
    kit: "AoE provoke knight. Old opener that still works in Gold.",
    defense: 7,
    offense: 5,
  },
  {
    id: "charlotte",
    name: "Charlotte",
    short: "Charlotte",
    element: "fire",
    class: "knight",
    tier: "A",
    roles: ["dps", "tank"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE knight. Extra attacks off a fat frontline.",
    defense: 6,
    offense: 7,
  },
  {
    id: "ilynav",
    name: "Ilynav",
    short: "Ilynav",
    element: "fire",
    class: "knight",
    tier: "S",
    roles: ["bruiser", "dps"],
    tags: ["extra-turn", "injury", "aoe"],
    kit: "Injury knight. Extra attacks that stack the long fight.",
    defense: 7,
    offense: 8,
  },
  {
    id: "ae-winter",
    name: "ae-WINTER",
    short: "ae-WINTER",
    element: "fire",
    class: "thief",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Limited AoE thief. Extra attacks if the first skill lands.",
    defense: 4,
    offense: 8,
  },
  {
    id: "haste",
    name: "Haste",
    short: "Haste",
    element: "fire",
    class: "soulweaver",
    tier: "B",
    roles: ["healer", "dps"],
    tags: ["unhealable", "aoe"],
    kit: "Unhealable soul weaver. Heals, then shuts down the wall’s sustain.",
    defense: 5,
    offense: 6,
  },
  {
    id: "kayron",
    name: "Kayron",
    short: "Kayron",
    element: "fire",
    class: "thief",
    tier: "A",
    roles: ["dps", "bruiser"],
    tags: ["extra-turn", "unhealable", "invincible"],
    kit: "Extinction thief. Invincible window, then extra attacks.",
    defense: 6,
    offense: 8,
  },
  {
    id: "swift-flagbearer-sigret",
    name: "Swift Flagbearer Sigret",
    short: "SF Sigret",
    element: "fire",
    class: "thief",
    tier: "S",
    roles: ["control", "opener"],
    tags: ["strip", "silence", "dual-attack"],
    kit: "Limited thief. Strip, target lock, then the team basic-attacks.",
    defense: 5,
    offense: 8,
  },
  {
    id: "tori",
    name: "Tori",
    short: "Tori",
    element: "fire",
    class: "thief",
    tier: "S",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "cr-push"],
    kit: "Extra-attack thief. Speed contest, then the cycle is hers.",
    defense: 4,
    offense: 9,
  },
  {
    id: "afternoon-soak-flan",
    name: "Afternoon Soak Flan",
    short: "AS Flan",
    element: "fire",
    class: "ranger",
    tier: "S",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn", "ignore-er"],
    kit: "Limited ranger. Ignore-ER extra attacks that end a cracked wall.",
    defense: 4,
    offense: 9,
  },
  {
    id: "beehoo",
    name: "Beehoo",
    short: "Beehoo",
    element: "fire",
    class: "ranger",
    tier: "B",
    roles: ["dps"],
    tags: ["extra-turn", "aoe"],
    kit: "Extra-attack ranger. Niche, still a closer if he lives.",
    defense: 4,
    offense: 7,
  },
  {
    id: "bomb-model-kanna",
    name: "Bomb Model Kanna",
    short: "BM Kanna",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "AoE extra-attack ranger. Bomb kit — the wall has to be dead after S3.",
    defense: 4,
    offense: 8,
  },
  {
    id: "elphelt",
    name: "Elphelt",
    short: "Elphelt",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["stun", "extra-turn", "aoe"],
    kit: "Stun ranger. Extra attacks if the first skill lands.",
    defense: 4,
    offense: 8,
  },
  {
    id: "lidica",
    name: "Lidica",
    short: "Lidica",
    element: "fire",
    class: "ranger",
    tier: "B",
    roles: ["opener", "control"],
    tags: ["cr-cut", "unhealable"],
    kit: "CR-cut opener. Old, still drafts into greedy speed teams.",
    defense: 4,
    offense: 7,
  },
  {
    id: "robin",
    name: "Robin",
    short: "Robin",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "control"],
    tags: ["extra-turn", "cr-push", "aoe"],
    kit: "Extra-attack ranger. CR push that starts the team’s cycle.",
    defense: 5,
    offense: 8,
  },
  {
    id: "ruiza",
    name: "Ruiza",
    short: "Ruiza",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["dps", "opener"],
    tags: ["extra-turn", "aoe", "cr-push"],
    kit: "Extra-attack ranger. Takes the cycle if she is left open.",
    defense: 4,
    offense: 8,
  },
  {
    id: "summertime-iseria",
    name: "Summertime Iseria",
    short: "ST Iseria",
    element: "fire",
    class: "ranger",
    tier: "A",
    roles: ["strip", "opener"],
    tags: ["strip", "defbreak", "aoe"],
    kit: "Limited strip ranger. Def-break plus strip — a clean summer opener.",
    defense: 4,
    offense: 8,
  },
  {
    id: "aramintha",
    name: "Aramintha",
    short: "Ara",
    element: "fire",
    class: "mage",
    tier: "B",
    roles: ["control", "dps"],
    tags: ["stun", "aoe", "unhealable"],
    kit: "AoE stun mage. Old, still a Gold control piece.",
    defense: 4,
    offense: 7,
  },
  {
    id: "baal-and-sezan",
    name: "Baal & Sezan",
    short: "B&S",
    element: "fire",
    class: "mage",
    tier: "B",
    roles: ["control", "dps"],
    tags: ["aoe", "stun"],
    kit: "AoE stun mage. Simple control if the wall is slow.",
    defense: 4,
    offense: 6,
  },
  {
    id: "festive-eda",
    name: "Festive Eda",
    short: "F.Eda",
    element: "fire",
    class: "mage",
    tier: "A",
    roles: ["dps", "cleave"],
    tags: ["aoe", "extra-turn"],
    kit: "Limited AoE mage. Extra attacks that end a cracked wall.",
    defense: 4,
    offense: 8,
  },
  {
    id: "kawerik",
    name: "Kawerik",
    short: "Kawerik",
    element: "fire",
    class: "mage",
    tier: "B",
    roles: ["strip", "dps"],
    tags: ["strip", "aoe"],
    kit: "AoE strip mage. Opens a buffed wall, then the closer finishes.",
    defense: 4,
    offense: 7,
  },
  {
    id: "melissa",
    name: "Melissa",
    short: "Melissa",
    element: "fire",
    class: "mage",
    tier: "A",
    roles: ["dps"],
    tags: ["extra-turn", "unhealable"],
    kit: "Extra-turn mage. Unhealable single-target — deletes the soul weaver.",
    defense: 4,
    offense: 8,
  },
  {
    id: "tenebria",
    name: "Tenebria",
    short: "Tenebria",
    element: "fire",
    class: "mage",
    tier: "B",
    roles: ["control", "dps"],
    tags: ["stun", "aoe"],
    kit: "AoE stun mage. Sleep plus stun — old control that still works.",
    defense: 4,
    offense: 7,
  },
  {
    id: "ae-ningning",
    name: "ae-NINGNING",
    short: "ae-NINGNING",
    element: "fire",
    class: "soulweaver",
    tier: "B",
    roles: ["healer", "cleanse"],
    tags: ["barrier", "cr-push"],
    kit: "Limited soul weaver. Barrier plus a push for the team.",
    defense: 6,
    offense: 5,
  },
  {
    id: "aram",
    name: "Aram",
    short: "Aram",
    element: "fire",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "CR soul weaver. Extra turns and a push that owns the mid-fight.",
    defense: 7,
    offense: 6,
  },
  {
    id: "ivana",
    name: "Ivana",
    short: "Ivana",
    element: "fire",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "unhealable", "barrier"],
    kit: "Anti-immortal soul weaver. Punishes revive and extinction walls.",
    defense: 7,
    offense: 6,
  },
  {
    id: "perfumer-byblis",
    name: "Perfumer Byblis",
    short: "P.Byblis",
    element: "fire",
    class: "soulweaver",
    tier: "S",
    roles: ["healer", "control"],
    tags: ["cr-push", "extra-turn", "barrier"],
    kit: "Limited soul weaver. Extra turns and a push that starts the cycle.",
    defense: 7,
    offense: 6,
  },
  {
    id: "shuna",
    name: "Shuna",
    short: "Shuna",
    element: "fire",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["immunity", "barrier"],
    kit: "Collab soul weaver. Immunity window plus sustain.",
    defense: 7,
    offense: 5,
  },
  {
    id: "tamarinne",
    name: "Tamarinne",
    short: "Tama",
    element: "fire",
    class: "soulweaver",
    tier: "A",
    roles: ["healer", "cleanse"],
    tags: ["cr-push", "immunity"],
    kit: "CR soul weaver. Idol form pushes the whole team.",
    defense: 6,
    offense: 5,
  },
];

export const HERO_BY_ID: Record<string, Hero> = Object.fromEntries(
  HEROES.map((h) => [h.id, h]),
);

export function getHero(id: string): Hero | undefined {
  return HERO_BY_ID[id];
}

export const ELEMENT_LABEL: Record<Hero["element"], string> = {
  fire: "Fire",
  ice: "Ice",
  earth: "Earth",
  light: "Light",
  dark: "Dark",
};

export const CLASS_LABEL: Record<Hero["class"], string> = {
  knight: "Knight",
  warrior: "Warrior",
  mage: "Mage",
  ranger: "Ranger",
  thief: "Thief",
  soulweaver: "Soul Weaver",
};

export const TIER_ORDER: Record<Hero["tier"], number> = {
  SS: 4,
  S: 3,
  A: 2,
  B: 1,
};

export const SAMPLE_ROSTER = [
  "boss-arunka",
  "empyrean-ilynav",
  "lady-of-the-scales",
  "rinak",
  "ruele-of-light",
  "harsetti",
  "briar-witch-iseria",
  "school-nurse-yulha",
  "new-moon-luna",
  "ambitious-tywin",
  "belian",
  "blood-moon-haste",
  "conqueror-lilias",
  "dragon-bride-senya",
  "fallen-cecilia",
  "frieren",
  "genesis-ras",
  "lone-wolf-peira",
  "last-rider-krau",
  "sea-phantom-politis",
  "setsuka",
  "navy-captain-landy",
  "remnant-violet",
  "ran",
  "apocalypse-ravi",
  "maid-chloe",
  "pirate-captain-flan",
  "straze",
  "zio",
  "zahhak",
  "mort",
  "krau",
  "diene",
  "solitaria",
  "milim",
  "mediator-kawerik",
  "flan",
  "peira",
  "landy",
  "roana",
  "senya",
  "lionheart-cermia",
  "hecate",
  "urban-shadow-choux",
] as const;

export const STARTER_ROSTER = [
  "adventurer-ras",
  "peira",
  "iseria",
  "flan",
  "straze",
  "zahhak",
  "milim",
  "diene",
  "krau",
  "senya",
  "fallen-cecilia",
  "ruele-of-light",
  "belian",
  "ran",
  "landy",
  "choux",
  "seaside-bellona",
  "tywin",
  "destina",
  "alencia",
  "apocalypse-ravi",
  "remnant-violet",
  "ambitious-tywin",
  "last-rider-krau",
] as const;
